export const COUNTRIES: Record<string, string[]> = {
  uz: [
    'Afg\'oniston', 'Albaniya', 'Jazoir', 'Andorra', 'Angola', 'Antigua va Barbuda',
    'Argentina', 'Armaniston', 'Avstraliya', 'Avstriya', 'Ozarbayjon',
    'Bagama orollari', 'Bahrayn', 'Bangladesh', 'Barbados', 'Belarus', 'Belgiya',
    'Beliz', 'Benin', 'Butan', 'Boliviya', 'Bosniya va Gersegovina', 'Botsvana',
    'Braziliya', 'Bruney', 'Bolgariya', 'Burkina-Faso', 'Burundi',
    'Kabo-Verde', 'Kambodja', 'Kamerun', 'Kanada', 'Markaziy Afrika Respublikasi',
    'Chad', 'Chili', 'Xitoy', 'Kolumbiya', 'Komor orollari', 'Kongo', 'Kosta-Rika',
    'Xorvatiya', 'Kuba', 'Kipr', 'Chexiya', 'Daniya', 'Jibuti', 'Dominika',
    'Dominikan Respublikasi', 'Sharqiy Timor',
    'Ekvador', 'Misr', 'Salvador', 'Ekvatorial Gvineya', 'Eritreya', 'Estoniya',
    'Eswatini', 'Efiopiya',
    'Fiji', 'Finlandiya', 'Fransiya',
    'Gabon', 'Gambiya', 'Gruziya', 'Germaniya', 'Gana', 'Gretsiya', 'Grenada',
    'Gvatemala', 'Gvineya', 'Gayana',
    'Gaiti', 'Gonduras', 'Vengriya',
    'Islandiya', 'Hindiston', 'Indoneziya', 'Eron', 'Iroq', 'Irlandiya', 'Isroil', 'Italiya',
    'Yamayka', 'Yaponiya', 'Iordaniya',
    'Qozog\'iston', 'Keniya', 'Kiribati', 'Quvayt', 'Qirg\'iziston',
    'Laos', 'Latviya', 'Livan', 'Lesoto', 'Liberiya', 'Liviya', 'Lixtenshteyn',
    'Litva', 'Lyuksemburg',
    'Madagaskar', 'Malavi', 'Malayziya', 'Maldiv orollari', 'Mali', 'Malta',
    'Marshall orollari', 'Mavritaniya', 'Mavrikiy', 'Meksika', 'Mikroneziya',
    'Moldova', 'Monako', 'Mo\'g\'uliston', 'Chernogoriya', 'Marokash', 'Mozambik', 'Myanma',
    'Namibiya', 'Nauru', 'Nepal', 'Niderlandiya', 'Yangi Zelandiya', 'Nikaragua',
    'Niger', 'Nigeriya', 'Shimoliy Koreya', 'Shimoliy Makedoniya', 'Norvegiya',
    'Ummon', 'Pokiston', 'Palau', 'Falastin', 'Panama', 'Papua Yangi Gvineya',
    'Paragvay', 'Peru', 'Filippin', 'Polsha', 'Portugaliya',
    'Qatar', 'Ruminiya', 'Rossiya', 'Ruanda',
    'Sent-Kits va Nevis', 'Sent-Lyusiya', 'Sent-Vinsent', 'Samoa', 'San-Marino',
    'San-Tome va Prinsipi', 'Saudiya Arabistoni', 'Senegal', 'Serbiya', 'Seyshel orollari',
    'Syerra-Leone', 'Singapur', 'Slovakiya', 'Sloveniya', 'Solomon orollari', 'Somaliya',
    'Janubiy Afrika', 'Janubiy Koreya', 'Janubiy Sudan', 'Ispaniya', 'Shri-Lanka',
    'Sudan', 'Surinam', 'Shvetsiya', 'Shveytsariya', 'Suriya',
    'Tayvan', 'Tojikiston', 'Tanzaniya', 'Tailand', 'Togo', 'Tonga',
    'Trinidad va Tobago', 'Tunis', 'Turkiya', 'Turkmaniston', 'Tuvalu',
    'Uganda', 'Ukraina', 'Birlashgan Arab Amirliklari', 'Buyuk Britaniya',
    'Amerika Qo\'shma Shtatlari', 'Urugvay', 'O\'zbekiston',
    'Vanuatu', 'Vatikan', 'Venesuela', 'Vyetnam',
    'Yaman', 'Zambiya', 'Zimbabve',
  ],
  ru: [
    'Афганистан', 'Албания', 'Алжир', 'Андорра', 'Ангола', 'Антигуа и Барбуда',
    'Аргентина', 'Армения', 'Австралия', 'Австрия', 'Азербайджан',
    'Багамские острова', 'Бахрейн', 'Бангладеш', 'Барбадос', 'Беларусь', 'Бельгия',
    'Белиз', 'Бенин', 'Бутан', 'Боливия', 'Босния и Герцеговина', 'Ботсвана',
    'Бразилия', 'Бруней', 'Болгария', 'Буркина-Фасо', 'Бурунди',
    'Кабо-Верде', 'Камбоджа', 'Камерун', 'Канада', 'Центральноафриканская Республика',
    'Чад', 'Чили', 'Китай', 'Колумбия', 'Коморские острова', 'Конго', 'Коста-Рика',
    'Хорватия', 'Куба', 'Кипр', 'Чехия', 'Дания', 'Джибути', 'Доминика',
    'Доминиканская Республика', 'Восточный Тимор',
    'Эквадор', 'Египет', 'Сальвадор', 'Экваториальная Гвинея', 'Эритрея', 'Эстония',
    'Эсватини', 'Эфиопия',
    'Фиджи', 'Финляндия', 'Франция',
    'Габон', 'Гамбия', 'Грузия', 'Германия', 'Гана', 'Греция', 'Гренада',
    'Гватемала', 'Гвинея', 'Гайана',
    'Гаити', 'Гондурас', 'Венгрия',
    'Исландия', 'Индия', 'Индонезия', 'Иран', 'Ирак', 'Ирландия', 'Израиль', 'Италия',
    'Ямайка', 'Япония', 'Иордания',
    'Казахстан', 'Кения', 'Кирибати', 'Кувейт', 'Кыргызстан',
    'Лаос', 'Латвия', 'Ливан', 'Лесото', 'Либерия', 'Ливия', 'Лихтенштейн',
    'Литва', 'Люксембург',
    'Мадагаскар', 'Малави', 'Малайзия', 'Мальдивы', 'Мали', 'Мальта',
    'Маршалловы острова', 'Мавритания', 'Маврикий', 'Мексика', 'Микронезия',
    'Молдова', 'Монако', 'Монголия', 'Черногория', 'Марокко', 'Мозамбик', 'Мьянма',
    'Намибия', 'Науру', 'Непал', 'Нидерланды', 'Новая Зеландия', 'Никарагуа',
    'Нигер', 'Нигерия', 'Северная Корея', 'Северная Македония', 'Норвегия',
    'Оман', 'Пакистан', 'Палау', 'Палестина', 'Панама', 'Папуа — Новая Гвинея',
    'Парагвай', 'Перу', 'Филиппины', 'Польша', 'Португалия',
    'Катар', 'Румыния', 'Россия', 'Руанда',
    'Сент-Китс и Невис', 'Сент-Люсия', 'Сент-Винсент', 'Самоа', 'Сан-Марино',
    'Сан-Томе и Принсипи', 'Саудовская Аравия', 'Сенегал', 'Сербия', 'Сейшельские острова',
    'Сьерра-Леоне', 'Сингапур', 'Словакия', 'Словения', 'Соломоновы острова', 'Сомали',
    'Южная Африка', 'Южная Корея', 'Южный Судан', 'Испания', 'Шри-Ланка',
    'Судан', 'Суринам', 'Швеция', 'Швейцария', 'Сирия',
    'Тайвань', 'Таджикистан', 'Танзания', 'Таиланд', 'Того', 'Тонга',
    'Тринидад и Тобаго', 'Тунис', 'Турция', 'Туркменистан', 'Тувалу',
    'Уганда', 'Украина', 'Объединённые Арабские Эмираты', 'Великобритания',
    'Соединённые Штаты Америки', 'Уругвай', 'Узбекистан',
    'Вануату', 'Ватикан', 'Венесуэла', 'Вьетнам',
    'Йемен', 'Замбия', 'Зимбабве',
  ],
};

export const CITIES_BY_COUNTRY: Record<string, Record<string, string[]>> = {
  uz: {
    'O\'zbekiston': ['Toshkent', 'Samarqand', 'Buxoro', 'Xiva', 'Nukus', 'Namangan', 'Andijon', 'Farg\'ona', 'Qarshi', 'Navoiy', 'Jizzax', 'Termiz', 'Urganch', 'Guliston', 'Kokand', 'Marg\'ilon', 'Shahrisabz', 'Chirchiq', 'Olmaliq'],
    'Turkiya': ['Istanbul', 'Antalya', 'Anqara', 'Izmir', 'Bodrum', 'Fethiye', 'Kemer', 'Marmaris', 'Alanya', 'Side', 'Belek', 'Kapadokiya', 'Pamukkale', 'Trabzon', 'Bursa', 'Kushadasi'],
    'Misr': ['Qohira', 'Sharm-el-Shayx', 'Hurgada', 'Aleksandriya', 'Luxor', 'Asuan', 'Dahab', 'Marsa Alam', 'Taba'],
    'Birlashgan Arab Amirliklari': ['Dubay', 'Abu Dabi', 'Sharjah', 'Ajman', 'Ras al-Xayma', 'Fujayra', 'Umm al-Quvvayn'],
    'Tailand': ['Bangkok', 'Pattaya', 'Phuket', 'Chiang May', 'Krabi', 'Ko Samui', 'Hua Hin', 'Ko Chang', 'Ko Lanta', 'Ko Phangan'],
    'Malayziya': ['Kuala Lumpur', 'Langkavi', 'Penang', 'Johor Bahru', 'Kota Kinabalu', 'Malakka', 'Ipoh', 'Kuching'],
    'Indoneziya': ['Bali', 'Jakarta', 'Yogyakarta', 'Lombok', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Labuan Bajo', 'Raja Ampat'],
    'Maldiv orollari': ['Male', 'Maafushi', 'Hulhumale', 'Addu', 'Fuvahmulah'],
    'Shri-Lanka': ['Kolombo', 'Kandy', 'Galle', 'Ella', 'Sigiriya', 'Nuvara Eliya', 'Bentota', 'Mirissa', 'Trinkomalee', 'Anuradhapura'],
    'Hindiston': ['Dehli', 'Mumbai', 'Goa', 'Jaipur', 'Agra', 'Varanasi', 'Kerala', 'Udaypur', 'Shimla', 'Darjiling', 'Amritsar', 'Kochi', 'Bangalore', 'Hyderabad', 'Chennai'],
    'Xitoy': ['Pekin', 'Shanxay', 'Guangjou', 'Shenzhen', 'Chengdu', 'Xian', 'Hangzhou', 'Guilin', 'Lhasa', 'Hongkong', 'Makao'],
    'Yaponiya': ['Tokio', 'Kyoto', 'Osaka', 'Xirosima', 'Nara', 'Yokohama', 'Sapporo', 'Fukuoka', 'Okinava', 'Kobe'],
    'Janubiy Koreya': ['Seul', 'Busan', 'Jeju', 'Inchon', 'Gyeongju', 'Daegu', 'Suvon'],
    'Vyetnam': ['Xanoy', 'Xo Shi Min', 'Da Nang', 'Halong Bay', 'Nha Trang', 'Hue', 'Phu Quok', 'Hoy An', 'Dalat', 'Sa Pa'],
    'Gruziya': ['Tbilisi', 'Batumi', 'Kutaisi', 'Mestia', 'Kazbegi', 'Sighnaghi', 'Borjomi', 'Gudauri', 'Telavi'],
    'Ozarbayjon': ['Boku', 'Gabala', 'Sheki', 'Quba', 'Lenkeran', 'Ganja', 'Mingachevir'],
    'Rossiya': ['Moskva', 'Sankt-Peterburg', 'Sochi', 'Kazan', 'Yekaterinburg', 'Novosibirsk', 'Kaliningrad', 'Vladivostok', 'Nizhny Novgorod', 'Krasnodar'],
    'Italiya': ['Rim', 'Milan', 'Venetsiya', 'Florensiya', 'Neapol', 'Amalfi', 'Palermo', 'Turin', 'Verona', 'Genuya', 'Boloniya', 'Piza'],
    'Fransiya': ['Parij', 'Nistsa', 'Lion', 'Marsel', 'Strasburg', 'Bordo', 'Monako', 'Kann', 'Tuluz'],
    'Ispaniya': ['Madrid', 'Barselona', 'Valensia', 'Sevilya', 'Malaga', 'Granada', 'Bilbao', 'Palma-de-Mayorka', 'Ibisa', 'Tenerife', 'San-Sebastyan', 'Alikante'],
    'Germaniya': ['Berlin', 'Munxen', 'Frankfurt', 'Gamburg', 'Kyoln', 'Dyusseldorf', 'Shtutgart', 'Drezden', 'Nyurnberg', 'Geydelberg'],
    'Buyuk Britaniya': ['London', 'Manchester', 'Edinburgh', 'Liverpul', 'Oksford', 'Kembrij', 'Bristol', 'Birmingem', 'Glasgow', 'Bath'],
    'Gretsiya': ['Afina', 'Santorini', 'Mikonos', 'Krit', 'Rodos', 'Saloniki', 'Korfu', 'Zakyntos', 'Kos'],
    'Saudiya Arabistoni': ['Riyod', 'Jidda', 'Makka', 'Madina', 'Dammam', 'Tabuk', 'Abha', 'Taif'],
    'Qozog\'iston': ['Ostona', 'Almati', 'Shimkent', 'Nur-Sulton', 'Turkiston', 'Aktau', 'Atirau', 'Qorag\'andin', 'Semey', 'Taldiqo\'rg\'on'],
    'Qirg\'iziston': ['Bishkek', 'Osh', 'Issiq-Ko\'l', 'Jalal-Obod', 'Karakol', 'Naryn', 'Tokmok'],
    'Tojikiston': ['Dushanbe', 'Xujand', 'Kulob', 'Boxter', 'Istaravshan', 'Panjakent', 'Xorug\''],
    'Turkmaniston': ['Ashgabat', 'Turkmanbashy', 'Mary', 'Dashoguz', 'Turkmenobod', 'Balkanobod', 'Avaza'],
    'Amerika Qo\'shma Shtatlari': ['Nyu-York', 'Los-Anjeles', 'Chikago', 'Mayami', 'Las-Vegas', 'San-Fransisko', 'Vashington', 'Boston', 'Syetl', 'Orlando', 'Xouston', 'Dallas', 'San-Diego', 'Gonolulu', 'Atlanta', 'Denver', 'Filadelfiya'],
    'Kanada': ['Toronto', 'Vankuver', 'Monreal', 'Ottava', 'Kalgari', 'Edmonton', 'Kvebek', 'Viktoriya'],
    'Braziliya': ['Rio-de-Janeyro', 'San-Paulu', 'Brazilia', 'Salvador', 'Fortaleza', 'Manaus', 'Resife'],
    'Meksika': ['Mexiko', 'Kankun', 'Playa del Karmen', 'Los Kabos', 'Gvadalaxara', 'Puerta Vayarta', 'Oaxaka', 'Merida', 'Tulum'],
    'Avstraliya': ['Sidney', 'Melburn', 'Brisben', 'Pert', 'Adelaida', 'Kanberra', 'Gold Kost', 'Keyns'],
    'Yangi Zelandiya': ['Oklend', 'Vellington', 'Kvinstaun', 'Kraystchurch', 'Rotorua', 'Dane\'din'],
    'Armaniston': ['Yerevan', 'Gyumri', 'Vanadzor', 'Dilijan', 'Jermuk', 'Sevan'],
    'Polsha': ['Varshava', 'Krakov', 'Gdansk', 'Vroslav', 'Poznan', 'Lyublin', 'Zakopane'],
    'Chexiya': ['Praga', 'Karlovi Vari', 'Brno', 'Chesky Krumlov', 'Plzen', 'Olomouts'],
    'Avstriya': ['Vena', 'Zalsburg', 'Innsbruck', 'Grats', 'Linz', 'Xallshtat'],
    'Shveytsariya': ['Syurix', 'Jeneva', 'Bern', 'Lyusern', 'Interlaken', 'Zermatt', 'Davos', 'Bazel'],
    'Portugaliya': ['Lissabon', 'Porto', 'Faro', 'Sintra', 'Madeyra', 'Algarve', 'Evora'],
    'Niderlandiya': ['Amsterdam', 'Rotterdam', 'Gaaga', 'Utreht', 'Delft', 'Leyden'],
    'Vengriya': ['Budapesht', 'Debretsen', 'Szeged', 'Pech', 'Eger'],
    'Xorvatiya': ['Zagreb', 'Dubrovnik', 'Split', 'Pula', 'Zadar', 'Xvar', 'Rovinj'],
    'Chernogoriya': ['Podgoritsa', 'Budva', 'Kotor', 'Tivat', 'Xerseg Novi', 'Sv. Stefan', 'Bar'],
    'Iordaniya': ['Amman', 'Petra', 'Aqaba', 'O\'lik dengiz', 'Jarash', 'Vadi Rum'],
    'Isroil': ['Tel-Aviv', 'Quddus', 'Xayfa', 'Eyilat', 'Nazaret', 'O\'lik dengiz'],
    'Livan': ['Bayrut', 'Biblos', 'Sayda', 'Tripoli', 'Baalbek'],
    'Kuba': ['Gavana', 'Varadero', 'Trinidad', 'Santiago-de-Kuba', 'Vinales', 'Kayo Koko'],
    'Dominikan Respublikasi': ['Punta Kana', 'Santo Domingo', 'La Romana', 'Puerto Plata', 'Samana', 'Bavaro'],
    'Singapur': ['Singapur'],
    'Filippin': ['Manila', 'Borakay', 'Sebu', 'Palavan', 'El Nido', 'Siargao', 'Bohol'],
    'Kipr': ['Nikosiya', 'Limassol', 'Larnaka', 'Paphos', 'Ayia Napa', 'Protaras'],
    'Janubiy Afrika': ['Keyp Taun', 'Yoxannesburg', 'Durban', 'Pretoriya', 'Kruger parki'],
    'Keniya': ['Nayrobi', 'Mombasa', 'Masai Mara', 'Nakuru', 'Diani'],
    'Tanzaniya': ['Dar es Salaam', 'Zanzibar', 'Arusha', 'Kilimanjaro', 'Serengeti'],
    'Marokash': ['Marrakesh', 'Fes', 'Kasablanka', 'Shefshaouen', 'Tangyer', 'Rabat', 'Agadir', 'Essaouira'],
    'Tunis': ['Tunis', 'Suss', 'Hammamet', 'Jirba', 'Monastir', 'Sidi Bu Said'],
    'Eron': ['Tehron', 'Isfahon', 'Sheraz', 'Tabriz', 'Mashhad', 'Yazd', 'Kish oroli'],
    'Qatar': ['Doha', 'Al Xor', 'Lusail'],
    'Bahrayn': ['Manama', 'Muharraq'],
    'Quvayt': ['Quvayt shahri'],
    'Ummon': ['Maskat', 'Salalah', 'Nizva', 'Sur'],
    'Kambodja': ['Phnom Pen', 'Siem Reap', 'Sianukville', 'Kampot', 'Battambang'],
    'Nepal': ['Katmandu', 'Pokhara', 'Chitvan', 'Lumbini', 'Nagarkot'],
    'Mo\'g\'uliston': ['Ulaanbaatar', 'Erdenet', 'Xovd'],
    'Bruney': ['Bandar Seri Begavan'],
    'Finlandiya': ['Xelsinki', 'Tampere', 'Turku', 'Rovaniemi', 'Oulu'],
    'Shvetsiya': ['Stokgolm', 'Gyoteborg', 'Malmyo', 'Uppsala'],
    'Norvegiya': ['Oslo', 'Bergen', 'Stavanger', 'Tromsyo', 'Budo'],
    'Daniya': ['Kopengagen', 'Orhus', 'Odense', 'Olborg'],
    'Islandiya': ['Reykyavik', 'Akureyri', 'Vik'],
    'Belgiya': ['Bryussel', 'Bryugge', 'Gent', 'Antverpen'],
    'Irlandiya': ['Dublin', 'Kork', 'Goluey', 'Limerick'],
    'Moldova': ['Kishinev', 'Benderi', 'Beltsi', 'Tiraspol'],
    'Belarus': ['Minsk', 'Brest', 'Grodno', 'Gomel', 'Vitebsk', 'Mogilev'],
    'Ukraina': ['Kiyev', 'Lvov', 'Odessa', 'Xarkov', 'Dnepr'],
    'Bolgariya': ['Sofiya', 'Varna', 'Burgas', 'Plovdiv', 'Nesebar', 'Sunny Beach'],
    'Ruminiya': ['Buxarest', 'Klyuj', 'Brashov', 'Timishoara', 'Sibiu', 'Konstansa'],
    'Serbiya': ['Belgrad', 'Novi Sad', 'Nish', 'Subotica'],
    'Albaniya': ['Tirana', 'Durres', 'Saranda', 'Vlore', 'Berat', 'Gjirokaster'],
    'Slovakiya': ['Bratislava', 'Kosice', 'Tatri'],
    'Sloveniya': ['Lyublyana', 'Bled', 'Piran', 'Maribor'],
    'Estoniya': ['Tallin', 'Tartu', 'Pyarnu'],
    'Latviya': ['Riga', 'Yurmala', 'Sigulda', 'Liepaya'],
    'Litva': ['Vilnyus', 'Kaunas', 'Klaypeda', 'Trakai'],
    'Kolumbiya': ['Bogota', 'Kartaxena', 'Medeljin', 'Kali', 'Santa Marta'],
    'Peru': ['Lima', 'Kusko', 'Machu Pikchu', 'Arequipa', 'Puno'],
    'Argentina': ['Buenos-Ayres', 'Mendosa', 'Bariloche', 'Iguasu', 'Ushuaya', 'Kordova'],
    'Chili': ['Santyago', 'Valparaiso', 'San-Pedro-de-Atakama', 'Pasxa oroli', 'Patagoniya'],
    'Ekvador': ['Kito', 'Guayakil', 'Galapagos orollari', 'Kuenka', 'Banyo'],
    'Kosta-Rika': ['San-Xose', 'Tamarindo', 'Manuel Antonio', 'Arenal', 'Puerto Viejo'],
    'Tayvan': ['Tayley', 'Kaoxsiung', 'Taychung', 'Xiualien', 'Tainan'],
  },
  ru: {
    'Узбекистан': ['Ташкент', 'Самарканд', 'Бухара', 'Хива', 'Нукус', 'Наманган', 'Андижан', 'Фергана', 'Карши', 'Навои', 'Джизак', 'Термез', 'Ургенч', 'Гулистан', 'Коканд', 'Маргилан', 'Шахрисабз', 'Чирчик', 'Алмалык'],
    'Турция': ['Стамбул', 'Анталья', 'Анкара', 'Измир', 'Бодрум', 'Фетхие', 'Кемер', 'Мармарис', 'Аланья', 'Сиде', 'Белек', 'Каппадокия', 'Памуккале', 'Трабзон', 'Бурса', 'Кушадасы'],
    'Египет': ['Каир', 'Шарм-эль-Шейх', 'Хургада', 'Александрия', 'Луксор', 'Асуан', 'Дахаб', 'Марса-Алам', 'Таба'],
    'Объединённые Арабские Эмираты': ['Дубай', 'Абу-Даби', 'Шарджа', 'Аджман', 'Рас-эль-Хайма', 'Фуджейра', 'Умм-эль-Кувейн'],
    'Таиланд': ['Бангкок', 'Паттайя', 'Пхукет', 'Чиангмай', 'Краби', 'Ко Самуи', 'Хуа Хин', 'Ко Чанг', 'Ко Ланта', 'Ко Пханган'],
    'Малайзия': ['Куала-Лумпур', 'Лангкави', 'Пенанг', 'Джохор-Бару', 'Кота-Кинабалу', 'Малакка', 'Ипох', 'Кучинг'],
    'Индонезия': ['Бали', 'Джакарта', 'Джокьякарта', 'Ломбок', 'Сурабая', 'Бандунг', 'Медан', 'Семаранг', 'Лабуан-Баджо', 'Раджа-Ампат'],
    'Мальдивы': ['Мале', 'Маафуши', 'Хулхумале', 'Адду', 'Фувамулах'],
    'Шри-Ланка': ['Коломбо', 'Канди', 'Галле', 'Элла', 'Сигирия', 'Нувара-Элия', 'Бентота', 'Мирисса', 'Тринкомали', 'Анурадхапура'],
    'Индия': ['Дели', 'Мумбаи', 'Гоа', 'Джайпур', 'Агра', 'Варанаси', 'Керала', 'Удайпур', 'Шимла', 'Дарджилинг', 'Амритсар', 'Кочи', 'Бангалор', 'Хайдарабад', 'Ченнаи'],
    'Китай': ['Пекин', 'Шанхай', 'Гуанчжоу', 'Шэньчжэнь', 'Чэнду', 'Сиань', 'Ханчжоу', 'Гуйлинь', 'Лхаса', 'Гонконг', 'Макао'],
    'Япония': ['Токио', 'Киото', 'Осака', 'Хиросима', 'Нара', 'Иокогама', 'Саппоро', 'Фукуока', 'Окинава', 'Кобе'],
    'Южная Корея': ['Сеул', 'Пусан', 'Чеджу', 'Инчхон', 'Кёнджу', 'Тэгу', 'Сувон'],
    'Вьетнам': ['Ханой', 'Хошимин', 'Дананг', 'Бухта Халонг', 'Нячанг', 'Хюэ', 'Фукуок', 'Хойан', 'Далат', 'Сапа'],
    'Грузия': ['Тбилиси', 'Батуми', 'Кутаиси', 'Местиа', 'Казбеги', 'Сигнахи', 'Боржоми', 'Гудаури', 'Телави'],
    'Азербайджан': ['Баку', 'Габала', 'Шеки', 'Губа', 'Ленкорань', 'Гянджа', 'Мингечевир'],
    'Россия': ['Москва', 'Санкт-Петербург', 'Сочи', 'Казань', 'Екатеринбург', 'Новосибирск', 'Калининград', 'Владивосток', 'Нижний Новгород', 'Краснодар'],
    'Италия': ['Рим', 'Милан', 'Венеция', 'Флоренция', 'Неаполь', 'Амальфи', 'Палермо', 'Турин', 'Верона', 'Генуя', 'Болонья', 'Пиза'],
    'Франция': ['Париж', 'Ницца', 'Лион', 'Марсель', 'Страсбург', 'Бордо', 'Монако', 'Канны', 'Тулуза'],
    'Испания': ['Мадрид', 'Барселона', 'Валенсия', 'Севилья', 'Малага', 'Гранада', 'Бильбао', 'Пальма-де-Майорка', 'Ибица', 'Тенерифе', 'Сан-Себастьян', 'Аликанте'],
    'Германия': ['Берлин', 'Мюнхен', 'Франкфурт', 'Гамбург', 'Кёльн', 'Дюссельдорф', 'Штутгарт', 'Дрезден', 'Нюрнберг', 'Гейдельберг'],
    'Великобритания': ['Лондон', 'Манчестер', 'Эдинбург', 'Ливерпуль', 'Оксфорд', 'Кембридж', 'Бристоль', 'Бирмингем', 'Глазго', 'Бат'],
    'Греция': ['Афины', 'Санторини', 'Миконос', 'Крит', 'Родос', 'Салоники', 'Корфу', 'Закинтос', 'Кос'],
    'Саудовская Аравия': ['Эр-Рияд', 'Джидда', 'Мекка', 'Медина', 'Даммам', 'Табук', 'Абха', 'Таиф'],
    'Казахстан': ['Астана', 'Алматы', 'Шымкент', 'Нур-Султан', 'Туркестан', 'Актау', 'Атырау', 'Караганда', 'Семей', 'Талдыкорган'],
    'Кыргызстан': ['Бишкек', 'Ош', 'Иссык-Куль', 'Джалал-Абад', 'Каракол', 'Нарын', 'Токмок'],
    'Таджикистан': ['Душанбе', 'Худжанд', 'Куляб', 'Бохтар', 'Истаравшан', 'Пенджикент', 'Хорог'],
    'Туркменистан': ['Ашхабад', 'Туркменбаши', 'Мары', 'Дашогуз', 'Туркменабад', 'Балканабад', 'Аваза'],
    'Соединённые Штаты Америки': ['Нью-Йорк', 'Лос-Анджелес', 'Чикаго', 'Майами', 'Лас-Вегас', 'Сан-Франциско', 'Вашингтон', 'Бостон', 'Сиэтл', 'Орландо', 'Хьюстон', 'Даллас', 'Сан-Диего', 'Гонолулу', 'Атланта', 'Денвер', 'Филадельфия'],
    'Канада': ['Торонто', 'Ванкувер', 'Монреаль', 'Оттава', 'Калгари', 'Эдмонтон', 'Квебек', 'Виктория'],
    'Бразилия': ['Рио-де-Жанейро', 'Сан-Паулу', 'Бразилиа', 'Сальвадор', 'Форталеза', 'Манаус', 'Ресифи'],
    'Мексика': ['Мехико', 'Канкун', 'Плая-дель-Кармен', 'Лос-Кабос', 'Гвадалахара', 'Пуэрто-Вальярта', 'Оахака', 'Мерида', 'Тулум'],
    'Австралия': ['Сидней', 'Мельбурн', 'Брисбен', 'Перт', 'Аделаида', 'Канберра', 'Голд-Кост', 'Кэрнс'],
    'Новая Зеландия': ['Окленд', 'Веллингтон', 'Квинстаун', 'Крайстчерч', 'Роторуа', 'Данидин'],
    'Армения': ['Ереван', 'Гюмри', 'Ванадзор', 'Дилижан', 'Джермук', 'Севан'],
    'Польша': ['Варшава', 'Краков', 'Гданьск', 'Вроцлав', 'Познань', 'Люблин', 'Закопане'],
    'Чехия': ['Прага', 'Карловы Вары', 'Брно', 'Чешский Крумлов', 'Пльзень', 'Оломоуц'],
    'Австрия': ['Вена', 'Зальцбург', 'Инсбрук', 'Грац', 'Линц', 'Хальштатт'],
    'Швейцария': ['Цюрих', 'Женева', 'Берн', 'Люцерн', 'Интерлакен', 'Церматт', 'Давос', 'Базель'],
    'Португалия': ['Лиссабон', 'Порту', 'Фару', 'Синтра', 'Мадейра', 'Алгарве', 'Эвора'],
    'Нидерланды': ['Амстердам', 'Роттердам', 'Гаага', 'Утрехт', 'Делфт', 'Лейден'],
    'Венгрия': ['Будапешт', 'Дебрецен', 'Сегед', 'Печ', 'Эгер'],
    'Хорватия': ['Загреб', 'Дубровник', 'Сплит', 'Пула', 'Задар', 'Хвар', 'Ровинь'],
    'Черногория': ['Подгорица', 'Будва', 'Котор', 'Тиват', 'Херцег-Нови', 'Святой Стефан', 'Бар'],
    'Иордания': ['Амман', 'Петра', 'Акаба', 'Мёртвое море', 'Джераш', 'Вади-Рам'],
    'Израиль': ['Тель-Авив', 'Иерусалим', 'Хайфа', 'Эйлат', 'Назарет', 'Мёртвое море'],
    'Ливан': ['Бейрут', 'Библос', 'Сайда', 'Триполи', 'Баальбек'],
    'Куба': ['Гавана', 'Варадеро', 'Тринидад', 'Сантьяго-де-Куба', 'Виньялес', 'Кайо-Коко'],
    'Доминиканская Республика': ['Пунта-Кана', 'Санто-Доминго', 'Ла-Романа', 'Пуэрто-Плата', 'Самана', 'Баваро'],
    'Сингапур': ['Сингапур'],
    'Филиппины': ['Манила', 'Боракай', 'Себу', 'Палаван', 'Эль-Нидо', 'Сиаргао', 'Бохол'],
    'Кипр': ['Никосия', 'Лимассол', 'Ларнака', 'Пафос', 'Айя-Напа', 'Протарас'],
    'Южная Африка': ['Кейптаун', 'Йоханнесбург', 'Дурбан', 'Претория', 'Парк Крюгера'],
    'Кения': ['Найроби', 'Момбаса', 'Масаи-Мара', 'Накуру', 'Диани'],
    'Танзания': ['Дар-эс-Салам', 'Занзибар', 'Аруша', 'Килиманджаро', 'Серенгети'],
    'Марокко': ['Марракеш', 'Фес', 'Касабланка', 'Шефшауэн', 'Танжер', 'Рабат', 'Агадир', 'Эссуэйра'],
    'Тунис': ['Тунис', 'Сусс', 'Хаммамет', 'Джерба', 'Монастир', 'Сиди-Бу-Саид'],
    'Иран': ['Тегеран', 'Исфахан', 'Шираз', 'Тебриз', 'Мешхед', 'Язд', 'Остров Киш'],
    'Катар': ['Доха', 'Аль-Хор', 'Лусаил'],
    'Бахрейн': ['Манама', 'Мухаррак'],
    'Кувейт': ['Эль-Кувейт'],
    'Оман': ['Маскат', 'Салала', 'Низва', 'Сур'],
    'Камбоджа': ['Пномпень', 'Сиемреап', 'Сиануквиль', 'Кампот', 'Баттамбанг'],
    'Непал': ['Катманду', 'Покхара', 'Читван', 'Лумбини', 'Нагаркот'],
    'Монголия': ['Улан-Батор', 'Эрдэнэт', 'Ховд'],
    'Бруней': ['Бандар-Сери-Бегаван'],
    'Финляндия': ['Хельсинки', 'Тампере', 'Турку', 'Рованиеми', 'Оулу'],
    'Швеция': ['Стокгольм', 'Гётеборг', 'Мальмё', 'Уппсала'],
    'Норвегия': ['Осло', 'Берген', 'Ставангер', 'Тромсё', 'Будё'],
    'Дания': ['Копенгаген', 'Орхус', 'Оденсе', 'Ольборг'],
    'Исландия': ['Рейкьявик', 'Акюрейри', 'Вик'],
    'Бельгия': ['Брюссель', 'Брюгге', 'Гент', 'Антверпен'],
    'Ирландия': ['Дублин', 'Корк', 'Голуэй', 'Лимерик'],
    'Молдова': ['Кишинёв', 'Бендеры', 'Бельцы', 'Тирасполь'],
    'Беларусь': ['Минск', 'Брест', 'Гродно', 'Гомель', 'Витебск', 'Могилёв'],
    'Украина': ['Киев', 'Львов', 'Одесса', 'Харьков', 'Днепр'],
    'Болгария': ['София', 'Варна', 'Бургас', 'Пловдив', 'Несебр', 'Солнечный берег'],
    'Румыния': ['Бухарест', 'Клуж', 'Брашов', 'Тимишоара', 'Сибиу', 'Констанца'],
    'Сербия': ['Белград', 'Нови-Сад', 'Ниш', 'Суботица'],
    'Албания': ['Тирана', 'Дуррес', 'Саранда', 'Влёра', 'Берат', 'Гирокастра'],
    'Словакия': ['Братислава', 'Кошице', 'Татры'],
    'Словения': ['Любляна', 'Блед', 'Пиран', 'Марибор'],
    'Эстония': ['Таллин', 'Тарту', 'Пярну'],
    'Латвия': ['Рига', 'Юрмала', 'Сигулда', 'Лиепая'],
    'Литва': ['Вильнюс', 'Каунас', 'Клайпеда', 'Тракай'],
    'Колумбия': ['Богота', 'Картахена', 'Медельин', 'Кали', 'Санта-Марта'],
    'Перу': ['Лима', 'Куско', 'Мачу-Пикчу', 'Арекипа', 'Пуно'],
    'Аргентина': ['Буэнос-Айрес', 'Мендоса', 'Барилоче', 'Игуасу', 'Ушуайя', 'Кордова'],
    'Чили': ['Сантьяго', 'Вальпараисо', 'Сан-Педро-де-Атакама', 'Остров Пасхи', 'Патагония'],
    'Эквадор': ['Кито', 'Гуаякиль', 'Галапагосские острова', 'Куэнка', 'Баньос'],
    'Коста-Рика': ['Сан-Хосе', 'Тамариндо', 'Мануэль-Антонио', 'Ареналь', 'Пуэрто-Вьехо'],
    'Тайвань': ['Тайбэй', 'Гаосюн', 'Тайчжун', 'Хуалянь', 'Тайнань'],
  },
};

export const AIRLINES: string[] = [
  // Central Asia & CIS
  'Uzbekistan Airways',
  'Silk Avia',
  'Qanot Sharq',
  'Air Astana',
  'FlyArystan',
  'SCAT Airlines',
  'Avia Traffic Company',
  'Pegasus Asia',
  'Tajik Air',
  'Somon Air',
  'Turkmenistan Airlines',
  'Azerbaijan Airlines (AZAL)',
  'Buta Airways',
  'Georgian Airways',
  'Armenia Aircompany (Fly Arna)',
  'Air Manas',
  'S7 Airlines',
  'Aeroflot',
  'Ural Airlines',
  'Rossiya Airlines',
  'Pobeda',
  'Nordwind Airlines',
  'Azur Air',
  'Red Wings Airlines',
  'Utair',
  'Yakutia Airlines',
  'Smartavia',
  'IrAero',
  'Belavia',
  'Air Moldova',
  'Ukraine International Airlines (UIA)',
  'SkyUp Airlines',
  'MIAT Mongolian Airlines',
  'Hunnu Air',

  // Turkey
  'Turkish Airlines',
  'Pegasus Airlines',
  'SunExpress',
  'AnadoluJet',
  'Corendon Airlines',
  'Onur Air',
  'Freebird Airlines',

  // Middle East & Gulf
  'Emirates',
  'Etihad Airways',
  'Qatar Airways',
  'flydubai',
  'Air Arabia',
  'Wizz Air Abu Dhabi',
  'Gulf Air',
  'Oman Air',
  'SalamAir',
  'Saudia (Saudi Arabian Airlines)',
  'flynas',
  'Flyadeal',
  'Kuwait Airways',
  'Jazeera Airways',
  'Middle East Airlines (MEA)',
  'Royal Jordanian',
  'Iran Air',
  'Mahan Air',
  'Iraq Airways',
  'EgyptAir',
  'Nile Air',
  'Air Cairo',

  // Asia - East
  'China Southern Airlines',
  'China Eastern Airlines',
  'Air China',
  'Hainan Airlines',
  'Sichuan Airlines',
  'Xiamen Airlines',
  'Shenzhen Airlines',
  'Spring Airlines',
  'Juneyao Airlines',
  'China Express Airlines',
  'Okay Airways',
  'Lucky Air',
  'Tianjin Airlines',
  'Beijing Capital Airlines',
  'Cathay Pacific',
  'HK Express',
  'Hong Kong Airlines',
  'Korean Air',
  'Asiana Airlines',
  'Jin Air',
  'Jeju Air',
  'T\'way Air',
  'Air Busan',
  'Easter Jet',
  'ANA (All Nippon Airways)',
  'Japan Airlines (JAL)',
  'Peach Aviation',
  'Jetstar Japan',
  'Skymark Airlines',
  'StarFlyer',
  'Solaseed Air',
  'Air Do',
  'EVA Air',
  'China Airlines',
  'Starlux Airlines',
  'Tigerair Taiwan',
  'Mandarin Airlines',

  // Asia - Southeast
  'Singapore Airlines',
  'Scoot',
  'Malaysia Airlines',
  'AirAsia',
  'AirAsia X',
  'Firefly',
  'Batik Air',
  'Batik Air Malaysia',
  'Thai Airways',
  'Thai AirAsia',
  'Bangkok Airways',
  'Thai Lion Air',
  'Thai Smile',
  'Nok Air',
  'Nok Scoot',
  'Vietnam Airlines',
  'VietJet Air',
  'Bamboo Airways',
  'Pacific Airlines',
  'Garuda Indonesia',
  'Lion Air',
  'Citilink',
  'Super Air Jet',
  'TransNusa',
  'Sriwijaya Air',
  'NAM Air',
  'Trigana Air Service',
  'Wings Air',
  'Philippine Airlines',
  'Cebu Pacific',
  'AirAsia Philippines',
  'Royal Air Philippines',
  'Myanmar Airways International',
  'Cambodia Angkor Air',
  'Lao Airlines',
  'Royal Brunei Airlines',

  // Asia - South
  'Air India',
  'IndiGo',
  'SpiceJet',
  'Go First',
  'Vistara',
  'AirAsia India',
  'Akasa Air',
  'Alliance Air',
  'SriLankan Airlines',
  'Maldivian',
  'Biman Bangladesh Airlines',
  'US-Bangla Airlines',
  'Nepal Airlines',
  'Buddha Air',
  'Yeti Airlines',
  'Pakistan International Airlines (PIA)',
  'Airblue',
  'Serene Air',

  // Europe - Major
  'Lufthansa',
  'British Airways',
  'Air France',
  'KLM Royal Dutch Airlines',
  'Iberia',
  'ITA Airways',
  'Swiss International Air Lines',
  'Austrian Airlines',
  'Brussels Airlines',
  'Scandinavian Airlines (SAS)',
  'Norwegian Air Shuttle',
  'Finnair',
  'LOT Polish Airlines',
  'TAP Air Portugal',
  'Aer Lingus',
  'Icelandair',
  'PLAY',
  'Aegean Airlines',
  'Olympic Air',
  'Air Serbia',
  'Croatia Airlines',
  'Air Baltic',
  'Czech Airlines',
  'TAROM',
  'Bulgaria Air',
  'Air Albania',
  'Luxair',
  'Air Malta',
  'Cyprus Airways',

  // Europe - Low Cost
  'Ryanair',
  'easyJet',
  'Wizz Air',
  'Vueling',
  'Eurowings',
  'Transavia',
  'Volotea',
  'Condor',
  'TUI fly',
  'Jet2',
  'Lauda',
  'Blue Air',
  'Flyr',
  'Norse Atlantic Airways',
  'Air Europa',
  'Iberia Express',
  'SmartWings',
  'Buzz',
  'Malta Air',
  'Sundair',

  // Africa
  'Ethiopian Airlines',
  'Kenya Airways',
  'South African Airways',
  'Royal Air Maroc',
  'Tunisair',
  'Air Algérie',
  'Rwandair',
  'Air Tanzania',
  'Uganda Airlines',
  'Air Côte d\'Ivoire',
  'ASKY Airlines',
  'Precision Air',
  'Air Mauritius',
  'Air Seychelles',
  'Air Madagascar',
  'Fastjet',
  'Jambojet',
  'FlySafair',
  'Kulula',
  'Air Peace',
  'Dana Air',
  'Overland Airways',
  'TAAG Angola Airlines',
  'LAM Mozambique',
  'Air Botswana',
  'Air Namibia',
  'Air Zimbabwe',
  'Eritrean Airlines',
  'Badr Airlines',

  // Americas - North
  'American Airlines',
  'United Airlines',
  'Delta Air Lines',
  'Southwest Airlines',
  'JetBlue Airways',
  'Alaska Airlines',
  'Spirit Airlines',
  'Frontier Airlines',
  'Hawaiian Airlines',
  'Allegiant Air',
  'Sun Country Airlines',
  'Breeze Airways',
  'Avelo Airlines',
  'Air Canada',
  'WestJet',
  'Porter Airlines',
  'Flair Airlines',
  'Swoop',
  'Aeromexico',
  'Volaris',
  'Viva Aerobus',

  // Americas - Latin & Caribbean
  'LATAM Airlines',
  'LATAM Airlines Brasil',
  'Gol Linhas Aéreas',
  'Azul Brazilian Airlines',
  'Avianca',
  'Copa Airlines',
  'Wingo',
  'JetSMART',
  'SKY Airline',
  'Aerolineas Argentinas',
  'Flybondi',
  'Caribbean Airlines',
  'Bahamasair',
  'Cubana de Aviación',
  'Air Caraïbes',

  // Oceania
  'Qantas',
  'Virgin Australia',
  'Jetstar Airways',
  'Rex Airlines',
  'Bonza',
  'Air New Zealand',
  'Fiji Airways',
  'Air Tahiti Nui',
  'Air Vanuatu',
  'Solomon Airlines',
  'Air Niugini',
  'Samoa Airways',
];
