export const COUNTRIES: Record<string, string[]> = {
  uz: [
    'Afg\'oniston', 'Albaniya', 'Jazoir', 'Andorra', 'Angola', 'Antigua va Barbuda',
    'Argentina', 'Armaniston', 'Avstraliya', 'Avstriya', 'Ozarbayjon',
    'Bagama orollari', 'Bahrayn', 'Bangladesh', 'Barbados', 'Belarus', 'Belgiya',
    'Beliz', 'Benin', 'Butan', 'Boliviya', 'Bosniya va Gersegovina', 'Botsvana',
    'Braziliya', 'Bruney', 'Bolgariya', 'Burkina-Faso', 'Burundi',
    'Kabo-Verde', 'Kambodja', 'Kamerun', 'Kanada', 'Markaziy Afrika Respublikasi',
    'Chad', 'Chili', 'Xitoy', 'Kolumbiya', 'Komor orollari', 'Kongo', 'Kosta-Rika',
    'Xorvatiya', 'Kuba', 'Kipr', 'Chexiya', 'Daniya', 'Jibuti', 'Dominika',
    'Dominikan Respublikasi', 'Sharqiy Timor',
    'Ekvador', 'Misr', 'Salvador', 'Ekvatorial Gvineya', 'Eritreya', 'Estoniya',
    'Eswatini', 'Efiopiya',
    'Fiji', 'Finlandiya', 'Fransiya',
    'Gabon', 'Gambiya', 'Gruziya', 'Germaniya', 'Gana', 'Gretsiya', 'Grenada',
    'Gvatemala', 'Gvineya', 'Gayana',
    'Gaiti', 'Gonduras', 'Vengriya',
    'Islandiya', 'Hindiston', 'Indoneziya', 'Eron', 'Iroq', 'Irlandiya', 'Isroil', 'Italiya',
    'Yamayka', 'Yaponiya', 'Iordaniya',
    'Qozog\'iston', 'Keniya', 'Kiribati', 'Quvayt', 'Qirg\'iziston',
    'Laos', 'Latviya', 'Livan', 'Lesoto', 'Liberiya', 'Liviya', 'Lixtenshteyn',
    'Litva', 'Lyuksemburg',
    'Madagaskar', 'Malavi', 'Malayziya', 'Maldiv orollari', 'Mali', 'Malta',
    'Marshall orollari', 'Mavritaniya', 'Mavrikiy', 'Meksika', 'Mikroneziya',
    'Moldova', 'Monako', 'Mo\'g\'uliston', 'Chernogoriya', 'Marokash', 'Mozambik', 'Myanma',
    'Namibiya', 'Nauru', 'Nepal', 'Niderlandiya', 'Yangi Zelandiya', 'Nikaragua',
    'Niger', 'Nigeriya', 'Shimoliy Koreya', 'Shimoliy Makedoniya', 'Norvegiya',
    'Ummon', 'Pokiston', 'Palau', 'Falastin', 'Panama', 'Papua Yangi Gvineya',
    'Paragvay', 'Peru', 'Filippin', 'Polsha', 'Portugaliya',
    'Qatar', 'Ruminiya', 'Rossiya', 'Ruanda',
    'Sent-Kits va Nevis', 'Sent-Lyusiya', 'Sent-Vinsent', 'Samoa', 'San-Marino',
    'San-Tome va Prinsipi', 'Saudiya Arabistoni', 'Senegal', 'Serbiya', 'Seyshel orollari',
    'Syerra-Leone', 'Singapur', 'Slovakiya', 'Sloveniya', 'Solomon orollari', 'Somaliya',
    'Janubiy Afrika', 'Janubiy Koreya', 'Janubiy Sudan', 'Ispaniya', 'Shri-Lanka',
    'Sudan', 'Surinam', 'Shvetsiya', 'Shveytsariya', 'Suriya',
    'Tayvan', 'Tojikiston', 'Tanzaniya', 'Tailand', 'Togo', 'Tonga',
    'Trinidad va Tobago', 'Tunis', 'Turkiya', 'Turkmaniston', 'Tuvalu',
    'Uganda', 'Ukraina', 'Birlashgan Arab Amirliklari', 'Buyuk Britaniya',
    'Amerika Qo\'shma Shtatlari', 'Urugvay', 'O\'zbekiston',
    'Vanuatu', 'Vatikan', 'Venesuela', 'Vyetnam',
    'Yaman', 'Zambiya', 'Zimbabve',
  ],
  ru: [
    'Афганистан', 'Албания', 'Алжир', 'Андорра', 'Ангола', 'Антигуа и Барбуда',
    'Аргентина', 'Армения', 'Австралия', 'Австрия', 'Азербайджан',
    'Багамские острова', 'Бахрейн', 'Бангладеш', 'Барбадос', 'Беларусь', 'Бельгия',
    'Белиз', 'Бенин', 'Бутан', 'Боливия', 'Босния и Герцеговина', 'Ботсвана',
    'Бразилия', 'Бруней', 'Болгария', 'Буркина-Фасо', 'Бурунди',
    'Кабо-Верде', 'Камбоджа', 'Камерун', 'Канада', 'Центральноафриканская Республика',
    'Чад', 'Чили', 'Китай', 'Колумбия', 'Коморские острова', 'Конго', 'Коста-Рика',
    'Хорватия', 'Куба', 'Кипр', 'Чехия', 'Дания', 'Джибути', 'Доминика',
    'Доминиканская Республика', 'Восточный Тимор',
    'Эквадор', 'Египет', 'Сальвадор', 'Экваториальная Гвинея', 'Эритрея', 'Эстония',
    'Эсватини', 'Эфиопия',
    'Фиджи', 'Финляндия', 'Франция',
    'Габон', 'Гамбия', 'Грузия', 'Германия', 'Гана', 'Греция', 'Гренада',
    'Гватемала', 'Гвинея', 'Гайана',
    'Гаити', 'Гондурас', 'Венгрия',
    'Исландия', 'Индия', 'Индонезия', 'Иран', 'Ирак', 'Ирландия', 'Израиль', 'Италия',
    'Ямайка', 'Япония', 'Иордания',
    'Казахстан', 'Кения', 'Кирибати', 'Кувейт', 'Кыргызстан',
    'Лаос', 'Латвия', 'Ливан', 'Лесото', 'Либерия', 'Ливия', 'Лихтенштейн',
    'Литва', 'Люксембург',
    'Мадагаскар', 'Малави', 'Малайзия', 'Мальдивы', 'Мали', 'Мальта',
    'Маршалловы острова', 'Мавритания', 'Маврикий', 'Мексика', 'Микронезия',
    'Молдова', 'Монако', 'Монголия', 'Черногория', 'Марокко', 'Мозамбик', 'Мьянма',
    'Намибия', 'Науру', 'Непал', 'Нидерланды', 'Новая Зеландия', 'Никарагуа',
    'Нигер', 'Нигерия', 'Северная Корея', 'Северная Македония', 'Норвегия',
    'Оман', 'Пакистан', 'Палау', 'Палестина', 'Панама', 'Папуа — Новая Гвинея',
    'Парагвай', 'Перу', 'Филиппины', 'Польша', 'Португалия',
    'Катар', 'Румыния', 'Россия', 'Руанда',
    'Сент-Китс и Невис', 'Сент-Люсия', 'Сент-Винсент', 'Самоа', 'Сан-Марино',
    'Сан-Томе и Принсипи', 'Саудовская Аравия', 'Сенегал', 'Сербия', 'Сейшельские острова',
    'Сьерра-Леоне', 'Сингапур', 'Словакия', 'Словения', 'Соломоновы острова', 'Сомали',
    'Южная Африка', 'Южная Корея', 'Южный Судан', 'Испания', 'Шри-Ланка',
    'Судан', 'Суринам', 'Швеция', 'Швейцария', 'Сирия',
    'Тайвань', 'Таджикистан', 'Танзания', 'Таиланд', 'Того', 'Тонга',
    'Тринидад и Тобаго', 'Тунис', 'Турция', 'Туркменистан', 'Тувалу',
    'Уганда', 'Украина', 'Объединённые Арабские Эмираты', 'Великобритания',
    'Соединённые Штаты Америки', 'Уругвай', 'Узбекистан',
    'Вануату', 'Ватикан', 'Венесуэла', 'Вьетнам',
    'Йемен', 'Замбия', 'Зимбабве',
  ],
};

export const CITIES_BY_COUNTRY: Record<string, Record<string, string[]>> = {
  uz: {
    // Markaziy Osiyo va MDH
    'O\'zbekiston': ['Toshkent', 'Samarqand', 'Buxoro', 'Xiva', 'Nukus', 'Namangan', 'Andijon', 'Farg\'ona', 'Qarshi', 'Navoiy', 'Jizzax', 'Termiz', 'Urganch', 'Guliston', 'Kokand', 'Marg\'ilon', 'Shahrisabz', 'Chirchiq', 'Olmaliq'],
    'Qozog\'iston': ['Ostona', 'Almati', 'Shimkent', 'Nur-Sulton', 'Turkiston', 'Aktau', 'Atirau', 'Qorag\'andin', 'Semey', 'Taldiqo\'rg\'on', 'Oral', 'Qostanay', 'Pavlodar', 'Aqto\'be'],
    'Qirg\'iziston': ['Bishkek', 'Osh', 'Issiq-Ko\'l', 'Jalal-Obod', 'Karakol', 'Naryn', 'Tokmok', 'Batken', 'Balykchy'],
    'Tojikiston': ['Dushanbe', 'Xujand', 'Kulob', 'Boxter', 'Istaravshan', 'Panjakent', 'Xorug\'', 'Tursunzoda', 'Konibodom'],
    'Turkmaniston': ['Ashgabat', 'Turkmanbashy', 'Mary', 'Dashoguz', 'Turkmenobod', 'Balkanobod', 'Avaza', 'Bayramali'],
    'Ozarbayjon': ['Boku', 'Gabala', 'Sheki', 'Quba', 'Lenkeran', 'Ganja', 'Mingachevir', 'Naftalan', 'Shamahi', 'Zagatala'],
    'Gruziya': ['Tbilisi', 'Batumi', 'Kutaisi', 'Mestia', 'Kazbegi', 'Sighnaghi', 'Borjomi', 'Gudauri', 'Telavi', 'Gori', 'Zugdidi'],
    'Armaniston': ['Yerevan', 'Gyumri', 'Vanadzor', 'Dilijan', 'Jermuk', 'Sevan', 'Goris', 'Tatev', 'Echmiadzin'],
    'Rossiya': ['Moskva', 'Sankt-Peterburg', 'Sochi', 'Kazan', 'Yekaterinburg', 'Novosibirsk', 'Kaliningrad', 'Vladivostok', 'Nizhny Novgorod', 'Krasnodar', 'Rostov-na-Donu', 'Samara', 'Ufa', 'Voronezh', 'Perm', 'Irkutsk', 'Murmansk'],
    'Belarus': ['Minsk', 'Brest', 'Grodno', 'Gomel', 'Vitebsk', 'Mogilev', 'Pinsk', 'Polotsk'],
    'Ukraina': ['Kiyev', 'Lvov', 'Odessa', 'Xarkov', 'Dnepr', 'Zaporojye', 'Vinnitsa', 'Ivano-Frankovsk', 'Uzhgorod', 'Chernivtsi'],
    'Moldova': ['Kishinev', 'Benderi', 'Beltsi', 'Tiraspol', 'Komrat', 'Orhey'],
    'Mo\'g\'uliston': ['Ulaanbaatar', 'Erdenet', 'Xovd', 'Darkhan', 'Choibalsan'],

    // Turkiya
    'Turkiya': ['Istanbul', 'Antalya', 'Anqara', 'Izmir', 'Bodrum', 'Fethiye', 'Kemer', 'Marmaris', 'Alanya', 'Side', 'Belek', 'Kapadokiya', 'Pamukkale', 'Trabzon', 'Bursa', 'Kushadasi', 'Gaziantep', 'Koniya', 'Samsun', 'Kayseriy'],

    // Yaqin Sharq va Ko'rfaz
    'Misr': ['Qohira', 'Sharm-el-Shayx', 'Hurgada', 'Aleksandriya', 'Luxor', 'Asuan', 'Dahab', 'Marsa Alam', 'Taba', 'El Gouna'],
    'Birlashgan Arab Amirliklari': ['Dubay', 'Abu Dabi', 'Sharjah', 'Ajman', 'Ras al-Xayma', 'Fujayra', 'Umm al-Quvvayn', 'Al Ayn'],
    'Saudiya Arabistoni': ['Riyod', 'Jidda', 'Makka', 'Madina', 'Dammam', 'Tabuk', 'Abha', 'Taif', 'Neom', 'Al Ula', 'Yanbu'],
    'Qatar': ['Doha', 'Al Xor', 'Lusail', 'Al Vaqra', 'Dukhan'],
    'Bahrayn': ['Manama', 'Muharraq', 'Riffa', 'Amvaj orollari'],
    'Quvayt': ['Quvayt shahri', 'Jahra', 'Ahmadi', 'Fahahil'],
    'Ummon': ['Maskat', 'Salalah', 'Nizva', 'Sur', 'Sohar', 'Musandam'],
    'Iordaniya': ['Amman', 'Petra', 'Aqaba', 'O\'lik dengiz', 'Jarash', 'Vadi Rum', 'Madaba', 'Ajlun'],
    'Isroil': ['Tel-Aviv', 'Quddus', 'Xayfa', 'Eyilat', 'Nazaret', 'O\'lik dengiz', 'Tveriya', 'Beer Sheva', 'Netaniya'],
    'Livan': ['Bayrut', 'Biblos', 'Sayda', 'Tripoli', 'Baalbek', 'Jun', 'Brummana'],
    'Eron': ['Tehron', 'Isfahon', 'Sheraz', 'Tabriz', 'Mashhad', 'Yazd', 'Kish oroli', 'Kerman', 'Qeshm', 'Hamadan'],
    'Iroq': ['Bag\'dod', 'Erbil', 'Basra', 'Sulaymaniyah', 'Najaf', 'Karbalo', 'Dahuk', 'Kirkuk', 'Mosul'],
    'Suriya': ['Damashq', 'Halab', 'Homs', 'Latakiya', 'Palmira', 'Tartus'],
    'Yaman': ['Sano', 'Adan', 'Taiz', 'Soqotra oroli', 'Al Mukalla'],
    'Falastin': ['Ramalloh', 'Baytulahm', 'G\'azo', 'Yerixo', 'Nablus', 'Xalil'],

    // Janubiy Osiyo
    'Hindiston': ['Dehli', 'Mumbai', 'Goa', 'Jaipur', 'Agra', 'Varanasi', 'Kerala', 'Udaypur', 'Shimla', 'Darjiling', 'Amritsar', 'Kochi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Mysore', 'Rishikesh', 'Haridvar', 'Ladakh'],
    'Pokiston': ['Islamobod', 'Karachi', 'Lahor', 'Peshovar', 'Faysalobod', 'Kvetta', 'Multon', 'Ravalpindi', 'Gilgit', 'Hunza'],
    'Bangladesh': ['Dakka', 'Chittagong', 'Silhet', 'Khulna', 'Rajshahi', 'Koks Bozor', 'Rangpur', 'Barisol'],
    'Shri-Lanka': ['Kolombo', 'Kandy', 'Galle', 'Ella', 'Sigiriya', 'Nuvara Eliya', 'Bentota', 'Mirissa', 'Trinkomalee', 'Anuradhapura', 'Polonnaruva', 'Yala'],
    'Maldiv orollari': ['Male', 'Maafushi', 'Hulhumale', 'Addu', 'Fuvahmulah', 'Rasdu', 'Thulusdhoo'],
    'Nepal': ['Katmandu', 'Pokhara', 'Chitvan', 'Lumbini', 'Nagarkot', 'Bhaktapur', 'Patan', 'Janakpur', 'Everest hududi'],
    'Butan': ['Thimphu', 'Paro', 'Punakha', 'Bumthang', 'Haa', 'Trongsa', 'Wangdue Phodrang'],

    // Sharqiy Osiyo
    'Xitoy': ['Pekin', 'Shanxay', 'Guangjou', 'Shenzhen', 'Chengdu', 'Xian', 'Hangzhou', 'Guilin', 'Lhasa', 'Hongkong', 'Makao', 'Nanjing', 'Kunming', 'Chongqing', 'Qingdao', 'Dalian', 'Xiamen', 'Suzhou', 'Harbin', 'Zhangjiajie'],
    'Yaponiya': ['Tokio', 'Kyoto', 'Osaka', 'Xirosima', 'Nara', 'Yokohama', 'Sapporo', 'Fukuoka', 'Okinava', 'Kobe', 'Nagoya', 'Kanazava', 'Nikko', 'Kamakura', 'Hakone', 'Miyajima'],
    'Janubiy Koreya': ['Seul', 'Busan', 'Jeju', 'Inchon', 'Gyeongju', 'Daegu', 'Suvon', 'Gangnam', 'Jeonju', 'Sokcho'],
    'Shimoliy Koreya': ['Pxenyan', 'Kaesong', 'Nampo', 'Vonsan', 'Sinuiju'],
    'Tayvan': ['Tayley', 'Kaoxsiung', 'Taychung', 'Xiualien', 'Tainan', 'Jiufen', 'Kenting', 'Sun Moon ko\'li', 'Taitung'],

    // Janubi-Sharqiy Osiyo
    'Tailand': ['Bangkok', 'Pattaya', 'Phuket', 'Chiang May', 'Krabi', 'Ko Samui', 'Hua Hin', 'Ko Chang', 'Ko Lanta', 'Ko Phangan', 'Chiang Ray', 'Pai', 'Ayutthaya', 'Kanchanaburi'],
    'Malayziya': ['Kuala Lumpur', 'Langkavi', 'Penang', 'Johor Bahru', 'Kota Kinabalu', 'Malakka', 'Ipoh', 'Kuching', 'Cameron Highlands', 'Tioman oroli', 'Perhentian orollari'],
    'Indoneziya': ['Bali', 'Jakarta', 'Yogyakarta', 'Lombok', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Labuan Bajo', 'Raja Ampat', 'Ubud', 'Nusa Penida', 'Flores', 'Sulawesi', 'Komodo'],
    'Vyetnam': ['Xanoy', 'Xo Shi Min', 'Da Nang', 'Halong Bay', 'Nha Trang', 'Hue', 'Phu Quok', 'Hoy An', 'Dalat', 'Sa Pa', 'Mui Ne', 'Ninh Binh', 'Phong Nha'],
    'Filippin': ['Manila', 'Borakay', 'Sebu', 'Palavan', 'El Nido', 'Siargao', 'Bohol', 'Koron', 'Puerto Prinsesa', 'Baguio', 'Vigan', 'Batanes'],
    'Kambodja': ['Phnom Pen', 'Siem Reap', 'Sianukville', 'Kampot', 'Battambang', 'Koh Rong', 'Kep'],
    'Myanma': ['Yangon', 'Mandalay', 'Bagan', 'Inle ko\'li', 'Naypyidaw', 'Ngapali', 'Hsipaw', 'Mrauk U'],
    'Laos': ['Vyentyan', 'Luang Prabang', 'Vang Vieng', 'Pakse', 'Savannakhet', 'Phongsali'],
    'Singapur': ['Singapur'],
    'Bruney': ['Bandar Seri Begavan', 'Temburong'],
    'Sharqiy Timor': ['Dili', 'Baukau', 'Maubisse'],

    // Yevropa - G'arbiy
    'Fransiya': ['Parij', 'Nistsa', 'Lion', 'Marsel', 'Strasburg', 'Bordo', 'Monako', 'Kann', 'Tuluz', 'Lil', 'Nant', 'Mont-Sen-Mishel', 'Provence', 'Korsika'],
    'Germaniya': ['Berlin', 'Munxen', 'Frankfurt', 'Gamburg', 'Kyoln', 'Dyusseldorf', 'Shtutgart', 'Drezden', 'Nyurnberg', 'Geydelberg', 'Leypsig', 'Bermen', 'Xannover'],
    'Buyuk Britaniya': ['London', 'Manchester', 'Edinburgh', 'Liverpul', 'Oksford', 'Kembrij', 'Bristol', 'Birmingem', 'Glasgow', 'Bath', 'York', 'Brighton', 'Kardiff', 'Belfast', 'Inverness', 'Stonehenge'],
    'Italiya': ['Rim', 'Milan', 'Venetsiya', 'Florensiya', 'Neapol', 'Amalfi', 'Palermo', 'Turin', 'Verona', 'Genuya', 'Boloniya', 'Piza', 'Sitsiliya', 'Sardiniya', 'Cinque Terre', 'Como ko\'li', 'Siena'],
    'Ispaniya': ['Madrid', 'Barselona', 'Valensia', 'Sevilya', 'Malaga', 'Granada', 'Bilbao', 'Palma-de-Mayorka', 'Ibisa', 'Tenerife', 'San-Sebastyan', 'Alikante', 'Kordoba', 'Toledo', 'Salamanka', 'Gran Kanariya'],
    'Portugaliya': ['Lissabon', 'Porto', 'Faro', 'Sintra', 'Madeyra', 'Algarve', 'Evora', 'Braga', 'Koimbra', 'Azor orollari'],
    'Niderlandiya': ['Amsterdam', 'Rotterdam', 'Gaaga', 'Utreht', 'Delft', 'Leyden', 'Xarlem', 'Maastricht', 'Eyindhoven', 'Groningen'],
    'Belgiya': ['Bryussel', 'Bryugge', 'Gent', 'Antverpen', 'Lyej', 'Dinant', 'Namur'],
    'Lyuksemburg': ['Lyuksemburg shahri', 'Vianden', 'Eshternaxa'],
    'Irlandiya': ['Dublin', 'Kork', 'Goluey', 'Limerick', 'Killarni', 'Klifz of Moher', 'Drogheda'],
    'Monako': ['Monako', 'Monte-Karlo'],

    // Yevropa - Shimoliy
    'Finlandiya': ['Xelsinki', 'Tampere', 'Turku', 'Rovaniemi', 'Oulu', 'Kuopio', 'Saariselka'],
    'Shvetsiya': ['Stokgolm', 'Gyoteborg', 'Malmyo', 'Uppsala', 'Kiruna', 'Visby', 'Lund'],
    'Norvegiya': ['Oslo', 'Bergen', 'Stavanger', 'Tromsyo', 'Budo', 'Lofoten orollari', 'Alesund', 'Trondheim', 'Nordkapp'],
    'Daniya': ['Kopengagen', 'Orhus', 'Odense', 'Olborg', 'Billund', 'Roskilde'],
    'Islandiya': ['Reykyavik', 'Akureyri', 'Vik', 'Husavik', 'Gullfoss', 'Geysir', 'Blue Lagoon'],

    // Yevropa - Sharqiy va Markaziy
    'Polsha': ['Varshava', 'Krakov', 'Gdansk', 'Vroslav', 'Poznan', 'Lyublin', 'Zakopane', 'Torun', 'Shtetsin', 'Lodz'],
    'Chexiya': ['Praga', 'Karlovi Vari', 'Brno', 'Chesky Krumlov', 'Plzen', 'Olomouts', 'Kutna Hora'],
    'Avstriya': ['Vena', 'Zalsburg', 'Innsbruck', 'Grats', 'Linz', 'Xallshtat', 'Kitzbuxel', 'Bregenz'],
    'Shveytsariya': ['Syurix', 'Jeneva', 'Bern', 'Lyusern', 'Interlaken', 'Zermatt', 'Davos', 'Bazel', 'Montryo', 'Lugano', 'Sankt-Moritz'],
    'Vengriya': ['Budapesht', 'Debretsen', 'Szeged', 'Pech', 'Eger', 'Vishegrad', 'Balaton ko\'li', 'Heviz'],
    'Ruminiya': ['Buxarest', 'Klyuj', 'Brashov', 'Timishoara', 'Sibiu', 'Konstansa', 'Sighisoara', 'Bran', 'Sinaya'],
    'Bolgariya': ['Sofiya', 'Varna', 'Burgas', 'Plovdiv', 'Nesebar', 'Sunny Beach', 'Veliko Tarnovo', 'Rila', 'Bansko'],
    'Xorvatiya': ['Zagreb', 'Dubrovnik', 'Split', 'Pula', 'Zadar', 'Xvar', 'Rovinj', 'Plitvitse ko\'llari', 'Korchula', 'Trogir'],
    'Serbiya': ['Belgrad', 'Novi Sad', 'Nish', 'Subotica', 'Kraguevats', 'Zlatibor'],
    'Chernogoriya': ['Podgoritsa', 'Budva', 'Kotor', 'Tivat', 'Xerseg Novi', 'Sv. Stefan', 'Bar', 'Ulsinj', 'Zablyak', 'Durmitor'],
    'Bosniya va Gersegovina': ['Sarayevo', 'Mostar', 'Banya Luka', 'Trebinye', 'Jaytse', 'Vishehrad'],
    'Albaniya': ['Tirana', 'Durres', 'Saranda', 'Vlore', 'Berat', 'Gjirokaster', 'Shkodra', 'Ksamil', 'Himara'],
    'Slovakiya': ['Bratislava', 'Kosice', 'Tatri', 'Banska Bystritsa', 'Nitra', 'Presov', 'Trentsin'],
    'Sloveniya': ['Lyublyana', 'Bled', 'Piran', 'Maribor', 'Portoroj', 'Postojna', 'Bohinj'],
    'Shimoliy Makedoniya': ['Skopye', 'Oxrid', 'Bitola', 'Ohrid ko\'li', 'Prilep', 'Shtip'],
    'Estoniya': ['Tallin', 'Tartu', 'Pyarnu', 'Saaremaa', 'Haapsalu', 'Narva'],
    'Latviya': ['Riga', 'Yurmala', 'Sigulda', 'Liepaya', 'Daugavpils', 'Tsesis', 'Ventspils'],
    'Litva': ['Vilnyus', 'Kaunas', 'Klaypeda', 'Trakai', 'Palanga', 'Shyaulyay', 'Nida'],
    'Andorra': ['Andorra-la-Velya', 'Encamp', 'Pas de la Casa', 'Soldeu'],
    'Lixtenshteyn': ['Vaduz', 'Shaan', 'Balzers'],
    'San-Marino': ['San-Marino shahri', 'Borgo Madjore'],
    'Vatikan': ['Vatikan shahri'],
    'Kipr': ['Nikosiya', 'Limassol', 'Larnaka', 'Paphos', 'Ayia Napa', 'Protaras', 'Famagusta'],
    'Gretsiya': ['Afina', 'Santorini', 'Mikonos', 'Krit', 'Rodos', 'Saloniki', 'Korfu', 'Zakyntos', 'Kos', 'Meteora', 'Delphi', 'Naxos', 'Paros', 'Lefkada'],
    'Malta': ['Valletta', 'Mdina', 'Sliema', 'St. Julian\'s', 'Gozo', 'Bugibba', 'Marsaxlokk'],

    // Shimoliy Amerika
    'Amerika Qo\'shma Shtatlari': ['Nyu-York', 'Los-Anjeles', 'Chikago', 'Mayami', 'Las-Vegas', 'San-Fransisko', 'Vashington', 'Boston', 'Syetl', 'Orlando', 'Xouston', 'Dallas', 'San-Diego', 'Gonolulu', 'Atlanta', 'Denver', 'Filadelfiya', 'Nashvil', 'Nyu-Orlean', 'Portlend', 'Feniks', 'Austin', 'Grand Kanyon'],
    'Kanada': ['Toronto', 'Vankuver', 'Monreal', 'Ottava', 'Kalgari', 'Edmonton', 'Kvebek', 'Viktoriya', 'Halifax', 'Banff', 'Vistler', 'Niagara sharshara', 'Winnipeg'],
    'Meksika': ['Mexiko', 'Kankun', 'Playa del Karmen', 'Los Kabos', 'Gvadalaxara', 'Puerta Vayarta', 'Oaxaka', 'Merida', 'Tulum', 'San Miguel de Allende', 'Guanajuato', 'Puebla', 'Bajas California'],

    // Janubiy Amerika
    'Braziliya': ['Rio-de-Janeyro', 'San-Paulu', 'Brazilia', 'Salvador', 'Fortaleza', 'Manaus', 'Resife', 'Florianopolis', 'Foz do Iguasu', 'Belo Horizonte', 'Kuritiba', 'Natal'],
    'Argentina': ['Buenos-Ayres', 'Mendosa', 'Bariloche', 'Iguasu', 'Ushuaya', 'Kordova', 'Salta', 'El Kalafate', 'Puerto Madryn', 'Rosario'],
    'Kolumbiya': ['Bogota', 'Kartaxena', 'Medeljin', 'Kali', 'Santa Marta', 'San Andres', 'Barrankilya', 'Pereira', 'Letisiya'],
    'Peru': ['Lima', 'Kusko', 'Machu Pikchu', 'Arequipa', 'Puno', 'Huaraz', 'Iquitos', 'Nazka', 'Titikaka ko\'li'],
    'Chili': ['Santyago', 'Valparaiso', 'San-Pedro-de-Atakama', 'Pasxa oroli', 'Patagoniya', 'Vinya del Mar', 'Puerto Natales', 'Torres del Payne'],
    'Ekvador': ['Kito', 'Guayakil', 'Galapagos orollari', 'Kuenka', 'Banyo', 'Otavalo', 'Montanita'],
    'Boliviya': ['La Pas', 'Sucre', 'Santa Krus', 'Uyuni', 'Cochabamba', 'Potosi', 'Oruro', 'Titikaka ko\'li'],
    'Venesuela': ['Karakas', 'Marakaybo', 'Margarita oroli', 'Valensia', 'Los Roques', 'Merida', 'Kanaima'],
    'Paragvay': ['Asunson', 'Syudad del Este', 'Enkarnasiyon', 'Areguya'],
    'Urugvay': ['Montevideo', 'Punta del Este', 'Kolonia del Sacramento', 'Salto'],
    'Surinam': ['Paramaribo', 'Nieuw Nickerie'],
    'Gayana': ['Jorjtaun', 'Kaieteur sharshara', 'Bartica', 'Linden'],

    // Markaziy Amerika va Karib
    'Kosta-Rika': ['San-Xose', 'Tamarindo', 'Manuel Antonio', 'Arenal', 'Puerto Viejo', 'Monteverdi', 'La Fortuna', 'Jaco'],
    'Panama': ['Panama shahri', 'Bokas del Toro', 'Boquete', 'San Blas orollari', 'Kolon', 'El-Valle', 'Pedasi'],
    'Gvatemala': ['Gvatemala shahri', 'Antigua', 'Flores', 'Chichicastenango', 'Atitlan ko\'li', 'Semuc Champey', 'Tikal'],
    'Kuba': ['Gavana', 'Varadero', 'Trinidad', 'Santiago-de-Kuba', 'Vinales', 'Kayo Koko', 'Kayo Santa Mariya', 'Syenfuegos'],
    'Dominikan Respublikasi': ['Punta Kana', 'Santo Domingo', 'La Romana', 'Puerto Plata', 'Samana', 'Bavaro', 'Jarabacoa', 'Sosua'],
    'Yamayka': ['Kingston', 'Montego Bay', 'Ocho Rios', 'Negril', 'Port Antonio', 'Rans Avey'],
    'Bagama orollari': ['Nassau', 'Freeport', 'Harbour Island', 'Exuma', 'Eleuthera', 'Grand Bahama'],
    'Barbados': ['Bridjtaun', 'Oistins', 'Holetown', 'Speightstown'],
    'Trinidad va Tobago': ['Port of Spain', 'San Fernando', 'Tobago', 'Scarborough', 'Crown Point'],
    'Antigua va Barbuda': ['Sent Jons', 'English Harbour', 'Dickenson Bay'],
    'Sent-Kits va Nevis': ['Basseterre', 'Charlestown'],
    'Sent-Lyusiya': ['Kastri', 'Soufriere', 'Rodney Bay', 'Marigot Bay'],
    'Sent-Vinsent': ['Kingstaun', 'Bequia', 'Mustique'],
    'Grenada': ['Sent-Jorj', 'Grand Anse', 'Carriacou'],
    'Dominika': ['Roseau', 'Portsmouth'],
    'Beliz': ['Beliz Siti', 'Belmopan', 'San Pedro', 'Caye Caulker', 'Placencia', 'Hopkins'],
    'Gonduras': ['Tegusigalpa', 'San Pedro Sula', 'Roatan', 'La Seyba', 'Utila', 'Copan'],
    'Nikaragua': ['Managua', 'Granada', 'Leon', 'San Xuan del Sur', 'Ometepe oroli', 'Corn orollari'],
    'Salvador': ['San Salvador', 'Santa Ana', 'El Tunco', 'Suchitoto', 'Joya de Seren'],

    // Afrika
    'Janubiy Afrika': ['Keyp Taun', 'Yoxannesburg', 'Durban', 'Pretoriya', 'Kruger parki', 'Stellenbosch', 'Garden Route', 'Port Elizabet', 'Knysna', 'Drakensberg'],
    'Marokash': ['Marrakesh', 'Fes', 'Kasablanka', 'Shefshaouen', 'Tangyer', 'Rabat', 'Agadir', 'Essaouira', 'Merzouga', 'Dades vodiysi'],
    'Tunis': ['Tunis', 'Suss', 'Hammamet', 'Jirba', 'Monastir', 'Sidi Bu Said', 'Douz', 'Kairouan', 'El Jem'],
    'Keniya': ['Nayrobi', 'Mombasa', 'Masai Mara', 'Nakuru', 'Diani', 'Malindi', 'Lamu', 'Amboseli', 'Naivasha'],
    'Tanzaniya': ['Dar es Salaam', 'Zanzibar', 'Arusha', 'Kilimanjaro', 'Serengeti', 'Ngorongoro', 'Stone Town', 'Pemba oroli', 'Selous'],
    'Efiopiya': ['Addis-Abeba', 'Lalibela', 'Gondar', 'Axum', 'Bahir Dar', 'Harar', 'Simien tog\'lari', 'Omo vodiysi'],
    'Uganda': ['Kampala', 'Entebbe', 'Jinja', 'Bwindi', 'Fort Portal', 'Mbale', 'Murchison sharshara'],
    'Ruanda': ['Kigali', 'Volcanoes milliy parki', 'Musanze', 'Ko\'l Kivu', 'Nyungwe', 'Butare'],
    'Madagaskar': ['Antananarivo', 'Nosy Be', 'Antsirabe', 'Morondava', 'Baobab xiyoboni', 'Ile Sainte-Marie'],
    'Namibiya': ['Vindhuk', 'Svakopmund', 'Etosha', 'Sossusvlei', 'Walvis Bay', 'Skeleton Coast', 'Fish River kanyon'],
    'Botsvana': ['Gaborone', 'Maun', 'Kasane', 'Chobe', 'Okavango deltasi', 'Francistaun', 'Nata'],
    'Mozambik': ['Maputu', 'Beyra', 'Inhambane', 'Vilankulo', 'Tofo', 'Bazaruto orollari'],
    'Zambiya': ['Lusaka', 'Livingston', 'Viktoriya sharshara', 'Kafue', 'Shimoliy Luangwa', 'Siavonga'],
    'Zimbabve': ['Harare', 'Bhulawayo', 'Viktoriya sharshara', 'Hwange', 'Masvingo', 'Matobo'],
    'Nigeriya': ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Enugu', 'Kaduna', 'Benin Siti'],
    'Gana': ['Akkra', 'Kumasi', 'Cape Coast', 'Tamale', 'Elmina', 'Mole milliy parki'],
    'Senegal': ['Dakar', 'Sent-Lui', 'Sali', 'Goree oroli', 'Casamance', 'Thies'],
    'Kamerun': ['Yaunde', 'Duala', 'Limbe', 'Bamenda', 'Kribi', 'Bafoussam'],
    'Jazoir': ['Jazoir shahri', 'Oron', 'Konstantin', 'Annaba', 'Setif', 'Tlemsen', 'Ghardaia'],
    'Liviya': ['Tripoli', 'Benghazi', 'Leptis Magna', 'Sabrata', 'Misrata'],
    'Mavrikiy': ['Port-Lui', 'Grand Baie', 'Flic en Flac', 'Bel Ombre', 'Tamarin', 'Rodriges oroli'],
    'Seyshel orollari': ['Viktoriya', 'Mahe', 'Praslin', 'La Digue', 'Silhouette oroli'],
    'Somaliya': ['Mogadishu', 'Hargeisa', 'Berbera'],
    'Sudan': ['Xartum', 'Omdurman', 'Port Sudan', 'Meroe', 'Kassala'],
    'Janubiy Sudan': ['Juba', 'Malakal', 'Bor'],
    'Eritreya': ['Asmara', 'Massaua', 'Keren'],
    'Jibuti': ['Jibuti shahri', 'Tadjura', 'Ali Sabieh'],
    'Mali': ['Bamako', 'Timbuktu', 'Djenne', 'Mopti', 'Segou'],
    'Niger': ['Niamey', 'Agadez', 'Zinder'],
    'Burkina-Faso': ['Uagadugu', 'Bobo Dioulasso'],
    'Chad': ['Njamena', 'Abeche', 'Moundou'],
    'Kongo': ['Brazzavil', 'Pointe-Noire'],
    'Gabon': ['Libreville', 'Port-Gentil', 'Lope milliy parki'],
    'Gambiya': ['Banjul', 'Serekunda', 'Bakau'],
    'Benin': ['Porto-Novo', 'Kotonou', 'Ouidah', 'Abomey'],
    'Togo': ['Lome', 'Kara', 'Sokode'],
    'Gvineya': ['Konakri', 'Nzerekore', 'Kankan'],
    'Syerra-Leone': ['Fritaun', 'Bo', 'Makeni'],
    'Liberiya': ['Monroviya', 'Buchanan'],
    'Markaziy Afrika Respublikasi': ['Bangi'],
    'Ekvatorial Gvineya': ['Malabo', 'Bata'],
    'Kabo-Verde': ['Praya', 'Mindelo', 'Sal', 'Boa Vista', 'Santo Antão'],
    'San-Tome va Prinsipi': ['San-Tome', 'Principe oroli'],
    'Komor orollari': ['Moroni', 'Mutsamudu'],
    'Burundi': ['Bujumbura', 'Gitega'],
    'Lesoto': ['Maseru', 'Thaba-Bosiu'],
    'Eswatini': ['Mbabane', 'Manzini', 'Ezulwini vodiysi'],
    'Malavi': ['Lilongve', 'Blantayr', 'Malavi ko\'li'],
    'Angola': ['Luanda', 'Benguela', 'Lobito', 'Huambo', 'Lubango'],
    'Gaiti': ['Port-o-Prens', 'Cap-Ayisyen', 'Jacmel'],

    // Okeaniya
    'Avstraliya': ['Sidney', 'Melburn', 'Brisben', 'Pert', 'Adelaida', 'Kanberra', 'Gold Kost', 'Keyns', 'Tasmanya', 'Darwin', 'Alice Springs', 'Buyuk to\'siq rif', 'Barossa vodiysi', 'Uluru'],
    'Yangi Zelandiya': ['Oklend', 'Vellington', 'Kvinstaun', 'Kraystchurch', 'Rotorua', 'Dane\'din', 'Taupo', 'Milford Saund', 'Xobbiton', 'Kaikoura', 'Abel Tasman'],
    'Fiji': ['Suva', 'Nadi', 'Denarau', 'Mamanuca orollari', 'Yasawa orollari', 'Coral Coast'],
    'Samoa': ['Apia', 'Savai\'i oroli'],
    'Tonga': ['Nukualofa', 'Vava\'u'],
    'Vanuatu': ['Port Vila', 'Luganville', 'Tanna oroli'],
    'Papua Yangi Gvineya': ['Port Moresbi', 'Lae', 'Mount Hagen', 'Goroka'],
    'Solomon orollari': ['Honiara', 'Gizo'],
    'Kiribati': ['Tarava', 'Christmas oroli'],
    'Marshall orollari': ['Majuro', 'Kwajalein'],
    'Mikroneziya': ['Palikir', 'Chuuk', 'Pohnpei'],
    'Palau': ['Koror', 'Jellyfish ko\'li', 'Rock Islands'],
    'Nauru': ['Yaren'],
    'Tuvalu': ['Funafuti'],
    'Mavritaniya': ['Nouakchott', 'Nouadhibou', 'Chinguetti'],
  },
  ru: {
    // Центральная Азия и СНГ
    'Узбекистан': ['Ташкент', 'Самарканд', 'Бухара', 'Хива', 'Нукус', 'Наманган', 'Андижан', 'Фергана', 'Карши', 'Навои', 'Джизак', 'Термез', 'Ургенч', 'Гулистан', 'Коканд', 'Маргилан', 'Шахрисабз', 'Чирчик', 'Алмалык'],
    'Казахстан': ['Астана', 'Алматы', 'Шымкент', 'Нур-Султан', 'Туркестан', 'Актау', 'Атырау', 'Караганда', 'Семей', 'Талдыкорган', 'Уральск', 'Костанай', 'Павлодар', 'Актобе'],
    'Кыргызстан': ['Бишкек', 'Ош', 'Иссык-Куль', 'Джалал-Абад', 'Каракол', 'Нарын', 'Токмок', 'Баткен', 'Балыкчы'],
    'Таджикистан': ['Душанбе', 'Худжанд', 'Куляб', 'Бохтар', 'Истаравшан', 'Пенджикент', 'Хорог', 'Турсунзаде', 'Канибадам'],
    'Туркменистан': ['Ашхабад', 'Туркменбаши', 'Мары', 'Дашогуз', 'Туркменабад', 'Балканабад', 'Аваза', 'Байрамали'],
    'Азербайджан': ['Баку', 'Габала', 'Шеки', 'Губа', 'Ленкорань', 'Гянджа', 'Мингечевир', 'Нафталан', 'Шамахы', 'Загатала'],
    'Грузия': ['Тбилиси', 'Батуми', 'Кутаиси', 'Местиа', 'Казбеги', 'Сигнахи', 'Боржоми', 'Гудаури', 'Телави', 'Гори', 'Зугдиди'],
    'Армения': ['Ереван', 'Гюмри', 'Ванадзор', 'Дилижан', 'Джермук', 'Севан', 'Горис', 'Татев', 'Эчмиадзин'],
    'Россия': ['Москва', 'Санкт-Петербург', 'Сочи', 'Казань', 'Екатеринбург', 'Новосибирск', 'Калининград', 'Владивосток', 'Нижний Новгород', 'Краснодар', 'Ростов-на-Дону', 'Самара', 'Уфа', 'Воронеж', 'Пермь', 'Иркутск', 'Мурманск'],
    'Беларусь': ['Минск', 'Брест', 'Гродно', 'Гомель', 'Витебск', 'Могилёв', 'Пинск', 'Полоцк'],
    'Украина': ['Киев', 'Львов', 'Одесса', 'Харьков', 'Днепр', 'Запорожье', 'Винница', 'Ивано-Франковск', 'Ужгород', 'Черновцы'],
    'Молдова': ['Кишинёв', 'Бендеры', 'Бельцы', 'Тирасполь', 'Комрат', 'Орхей'],
    'Монголия': ['Улан-Батор', 'Эрдэнэт', 'Ховд', 'Дархан', 'Чойбалсан'],

    // Турция
    'Турция': ['Стамбул', 'Анталья', 'Анкара', 'Измир', 'Бодрум', 'Фетхие', 'Кемер', 'Мармарис', 'Аланья', 'Сиде', 'Белек', 'Каппадокия', 'Памуккале', 'Трабзон', 'Бурса', 'Кушадасы', 'Газиантеп', 'Конья', 'Самсун', 'Кайсери'],

    // Ближний Восток и Залив
    'Египет': ['Каир', 'Шарм-эль-Шейх', 'Хургада', 'Александрия', 'Луксор', 'Асуан', 'Дахаб', 'Марса-Алам', 'Таба', 'Эль-Гуна'],
    'Объединённые Арабские Эмираты': ['Дубай', 'Абу-Даби', 'Шарджа', 'Аджман', 'Рас-эль-Хайма', 'Фуджейра', 'Умм-эль-Кувейн', 'Аль-Айн'],
    'Саудовская Аравия': ['Эр-Рияд', 'Джидда', 'Мекка', 'Медина', 'Даммам', 'Табук', 'Абха', 'Таиф', 'Неом', 'Аль-Ула', 'Янбу'],
    'Катар': ['Доха', 'Аль-Хор', 'Лусаил', 'Аль-Вакра', 'Духан'],
    'Бахрейн': ['Манама', 'Мухаррак', 'Рифа', 'Острова Амваж'],
    'Кувейт': ['Эль-Кувейт', 'Джахра', 'Ахмади', 'Фахахил'],
    'Оман': ['Маскат', 'Салала', 'Низва', 'Сур', 'Сохар', 'Мусандам'],
    'Иордания': ['Амман', 'Петра', 'Акаба', 'Мёртвое море', 'Джераш', 'Вади-Рам', 'Мадаба', 'Аджлун'],
    'Израиль': ['Тель-Авив', 'Иерусалим', 'Хайфа', 'Эйлат', 'Назарет', 'Мёртвое море', 'Тверия', 'Беэр-Шева', 'Нетания'],
    'Ливан': ['Бейрут', 'Библос', 'Сайда', 'Триполи', 'Баальбек', 'Джуния', 'Бруммана'],
    'Иран': ['Тегеран', 'Исфахан', 'Шираз', 'Тебриз', 'Мешхед', 'Язд', 'Остров Киш', 'Керман', 'Кешм', 'Хамадан'],
    'Ирак': ['Багдад', 'Эрбиль', 'Басра', 'Сулеймания', 'Наджаф', 'Кербела', 'Дахук', 'Киркук', 'Мосул'],
    'Сирия': ['Дамаск', 'Алеппо', 'Хомс', 'Латакия', 'Пальмира', 'Тартус'],
    'Йемен': ['Сана', 'Аден', 'Таиз', 'Остров Сокотра', 'Аль-Мукалла'],
    'Палестина': ['Рамалла', 'Вифлеем', 'Газа', 'Иерихон', 'Наблус', 'Хеврон'],

    // Южная Азия
    'Индия': ['Дели', 'Мумбаи', 'Гоа', 'Джайпур', 'Агра', 'Варанаси', 'Керала', 'Удайпур', 'Шимла', 'Дарджилинг', 'Амритсар', 'Кочи', 'Бангалор', 'Хайдарабад', 'Ченнаи', 'Калькутта', 'Пуна', 'Ахмедабад', 'Майсур', 'Ришикеш', 'Харидвар', 'Ладакх'],
    'Пакистан': ['Исламабад', 'Карачи', 'Лахор', 'Пешавар', 'Файсалабад', 'Кветта', 'Мултан', 'Равалпинди', 'Гилгит', 'Хунза'],
    'Бангладеш': ['Дакка', 'Читтагонг', 'Силхет', 'Кхулна', 'Раджшахи', 'Кокс-Базар', 'Рангпур', 'Барисал'],
    'Шри-Ланка': ['Коломбо', 'Канди', 'Галле', 'Элла', 'Сигирия', 'Нувара-Элия', 'Бентота', 'Мирисса', 'Тринкомали', 'Анурадхапура', 'Полоннарува', 'Яла'],
    'Мальдивы': ['Мале', 'Маафуши', 'Хулхумале', 'Адду', 'Фувамулах', 'Расду', 'Тулусду'],
    'Непал': ['Катманду', 'Покхара', 'Читван', 'Лумбини', 'Нагаркот', 'Бхактапур', 'Патан', 'Джанакпур', 'Регион Эвереста'],
    'Бутан': ['Тхимпху', 'Паро', 'Пунакха', 'Бумтанг', 'Хаа', 'Тронгса', 'Вангди-Пходранг'],

    // Восточная Азия
    'Китай': ['Пекин', 'Шанхай', 'Гуанчжоу', 'Шэньчжэнь', 'Чэнду', 'Сиань', 'Ханчжоу', 'Гуйлинь', 'Лхаса', 'Гонконг', 'Макао', 'Нанкин', 'Куньмин', 'Чунцин', 'Циндао', 'Далянь', 'Сямынь', 'Сучжоу', 'Харбин', 'Чжанцзяцзе'],
    'Япония': ['Токио', 'Киото', 'Осака', 'Хиросима', 'Нара', 'Иокогама', 'Саппоро', 'Фукуока', 'Окинава', 'Кобе', 'Нагоя', 'Канадзава', 'Никко', 'Камакура', 'Хаконэ', 'Миядзима'],
    'Южная Корея': ['Сеул', 'Пусан', 'Чеджу', 'Инчхон', 'Кёнджу', 'Тэгу', 'Сувон', 'Каннам', 'Чонджу', 'Сокчо'],
    'Северная Корея': ['Пхеньян', 'Кэсон', 'Нампхо', 'Вонсан', 'Синыйджу'],
    'Тайвань': ['Тайбэй', 'Гаосюн', 'Тайчжун', 'Хуалянь', 'Тайнань', 'Цзюфэнь', 'Кэньдин', 'Озеро Солнца и Луны', 'Тайтун'],

    // Юго-Восточная Азия
    'Таиланд': ['Бангкок', 'Паттайя', 'Пхукет', 'Чиангмай', 'Краби', 'Ко Самуи', 'Хуа Хин', 'Ко Чанг', 'Ко Ланта', 'Ко Пханган', 'Чианграй', 'Пай', 'Аюттхая', 'Канчанабури'],
    'Малайзия': ['Куала-Лумпур', 'Лангкави', 'Пенанг', 'Джохор-Бару', 'Кота-Кинабалу', 'Малакка', 'Ипох', 'Кучинг', 'Камерон-Хайлендс', 'Остров Тиоман', 'Острова Перхентиан'],
    'Индонезия': ['Бали', 'Джакарта', 'Джокьякарта', 'Ломбок', 'Сурабая', 'Бандунг', 'Медан', 'Семаранг', 'Лабуан-Баджо', 'Раджа-Ампат', 'Убуд', 'Нуса-Пенида', 'Флорес', 'Сулавеси', 'Комодо'],
    'Вьетнам': ['Ханой', 'Хошимин', 'Дананг', 'Бухта Халонг', 'Нячанг', 'Хюэ', 'Фукуок', 'Хойан', 'Далат', 'Сапа', 'Муйне', 'Ниньбинь', 'Фонгня'],
    'Филиппины': ['Манила', 'Боракай', 'Себу', 'Палаван', 'Эль-Нидо', 'Сиаргао', 'Бохол', 'Корон', 'Пуэрто-Принцесса', 'Багио', 'Виган', 'Батанес'],
    'Камбоджа': ['Пномпень', 'Сиемреап', 'Сиануквиль', 'Кампот', 'Баттамбанг', 'Ко Ронг', 'Кеп'],
    'Мьянма': ['Янгон', 'Мандалай', 'Баган', 'Озеро Инле', 'Нейпьидо', 'Нгапали', 'Сипо', 'Мраук-У'],
    'Лаос': ['Вьентьян', 'Луангпхабанг', 'Вангвьенг', 'Паксе', 'Саваннакхет', 'Пхонгсали'],
    'Сингапур': ['Сингапур'],
    'Бруней': ['Бандар-Сери-Бегаван', 'Тембуронг'],
    'Восточный Тимор': ['Дили', 'Баукау', 'Маубиссе'],

    // Западная Европа
    'Франция': ['Париж', 'Ницца', 'Лион', 'Марсель', 'Страсбург', 'Бордо', 'Монако', 'Канны', 'Тулуза', 'Лилль', 'Нант', 'Мон-Сен-Мишель', 'Прованс', 'Корсика'],
    'Германия': ['Берлин', 'Мюнхен', 'Франкфурт', 'Гамбург', 'Кёльн', 'Дюссельдорф', 'Штутгарт', 'Дрезден', 'Нюрнберг', 'Гейдельберг', 'Лейпциг', 'Бремен', 'Ганновер'],
    'Великобритания': ['Лондон', 'Манчестер', 'Эдинбург', 'Ливерпуль', 'Оксфорд', 'Кембридж', 'Бристоль', 'Бирмингем', 'Глазго', 'Бат', 'Йорк', 'Брайтон', 'Кардифф', 'Белфаст', 'Инвернесс', 'Стоунхендж'],
    'Италия': ['Рим', 'Милан', 'Венеция', 'Флоренция', 'Неаполь', 'Амальфи', 'Палермо', 'Турин', 'Верона', 'Генуя', 'Болонья', 'Пиза', 'Сицилия', 'Сардиния', 'Чинкве-Терре', 'Озеро Комо', 'Сиена'],
    'Испания': ['Мадрид', 'Барселона', 'Валенсия', 'Севилья', 'Малага', 'Гранада', 'Бильбао', 'Пальма-де-Майорка', 'Ибица', 'Тенерифе', 'Сан-Себастьян', 'Аликанте', 'Кордова', 'Толедо', 'Саламанка', 'Гран-Канария'],
    'Португалия': ['Лиссабон', 'Порту', 'Фару', 'Синтра', 'Мадейра', 'Алгарве', 'Эвора', 'Брага', 'Коимбра', 'Азорские острова'],
    'Нидерланды': ['Амстердам', 'Роттердам', 'Гаага', 'Утрехт', 'Делфт', 'Лейден', 'Харлем', 'Маастрихт', 'Эйндховен', 'Гронинген'],
    'Бельгия': ['Брюссель', 'Брюгге', 'Гент', 'Антверпен', 'Льеж', 'Динан', 'Намюр'],
    'Люксембург': ['Люксембург', 'Вианден', 'Эхтернах'],
    'Ирландия': ['Дублин', 'Корк', 'Голуэй', 'Лимерик', 'Килларни', 'Утёсы Мохер', 'Дрохеда'],
    'Монако': ['Монако', 'Монте-Карло'],

    // Северная Европа
    'Финляндия': ['Хельсинки', 'Тампере', 'Турку', 'Рованиеми', 'Оулу', 'Куопио', 'Саариселька'],
    'Швеция': ['Стокгольм', 'Гётеборг', 'Мальмё', 'Уппсала', 'Кируна', 'Висбю', 'Лунд'],
    'Норвегия': ['Осло', 'Берген', 'Ставангер', 'Тромсё', 'Будё', 'Лофотенские острова', 'Олесунн', 'Тронхейм', 'Нордкап'],
    'Дания': ['Копенгаген', 'Орхус', 'Оденсе', 'Ольборг', 'Биллунн', 'Роскилле'],
    'Исландия': ['Рейкьявик', 'Акюрейри', 'Вик', 'Хусавик', 'Гюдльфосс', 'Гейзер', 'Голубая лагуна'],

    // Восточная и Центральная Европа
    'Польша': ['Варшава', 'Краков', 'Гданьск', 'Вроцлав', 'Познань', 'Люблин', 'Закопане', 'Торунь', 'Щецин', 'Лодзь'],
    'Чехия': ['Прага', 'Карловы Вары', 'Брно', 'Чешский Крумлов', 'Пльзень', 'Оломоуц', 'Кутна-Гора'],
    'Австрия': ['Вена', 'Зальцбург', 'Инсбрук', 'Грац', 'Линц', 'Хальштатт', 'Кицбюэль', 'Брегенц'],
    'Швейцария': ['Цюрих', 'Женева', 'Берн', 'Люцерн', 'Интерлакен', 'Церматт', 'Давос', 'Базель', 'Монтрё', 'Лугано', 'Санкт-Мориц'],
    'Венгрия': ['Будапешт', 'Дебрецен', 'Сегед', 'Печ', 'Эгер', 'Вишеград', 'Озеро Балатон', 'Хевиз'],
    'Румыния': ['Бухарест', 'Клуж', 'Брашов', 'Тимишоара', 'Сибиу', 'Констанца', 'Сигишоара', 'Бран', 'Синая'],
    'Болгария': ['София', 'Варна', 'Бургас', 'Пловдив', 'Несебр', 'Солнечный берег', 'Велико-Тырново', 'Рила', 'Банско'],
    'Хорватия': ['Загреб', 'Дубровник', 'Сплит', 'Пула', 'Задар', 'Хвар', 'Ровинь', 'Плитвицкие озёра', 'Корчула', 'Трогир'],
    'Сербия': ['Белград', 'Нови-Сад', 'Ниш', 'Суботица', 'Крагуевац', 'Златибор'],
    'Черногория': ['Подгорица', 'Будва', 'Котор', 'Тиват', 'Херцег-Нови', 'Святой Стефан', 'Бар', 'Улцинь', 'Жабляк', 'Дурмитор'],
    'Босния и Герцеговина': ['Сараево', 'Мостар', 'Баня-Лука', 'Требинье', 'Яйце', 'Вышеград'],
    'Албания': ['Тирана', 'Дуррес', 'Саранда', 'Влёра', 'Берат', 'Гирокастра', 'Шкодер', 'Ксамиль', 'Химара'],
    'Словакия': ['Братислава', 'Кошице', 'Татры', 'Банска-Бистрица', 'Нитра', 'Прешов', 'Тренчин'],
    'Словения': ['Любляна', 'Блед', 'Пиран', 'Марибор', 'Порторож', 'Постойна', 'Бохинь'],
    'Северная Македония': ['Скопье', 'Охрид', 'Битола', 'Охридское озеро', 'Прилеп', 'Штип'],
    'Эстония': ['Таллин', 'Тарту', 'Пярну', 'Сааремаа', 'Хаапсалу', 'Нарва'],
    'Латвия': ['Рига', 'Юрмала', 'Сигулда', 'Лиепая', 'Даугавпилс', 'Цесис', 'Вентспилс'],
    'Литва': ['Вильнюс', 'Каунас', 'Клайпеда', 'Тракай', 'Паланга', 'Шяуляй', 'Нида'],
    'Андорра': ['Андорра-ла-Велья', 'Энкамп', 'Пас-де-ла-Каса', 'Сольдеу'],
    'Лихтенштейн': ['Вадуц', 'Шан', 'Бальцерс'],
    'Сан-Марино': ['Сан-Марино', 'Борго-Маджоре'],
    'Ватикан': ['Ватикан'],
    'Кипр': ['Никосия', 'Лимассол', 'Ларнака', 'Пафос', 'Айя-Напа', 'Протарас', 'Фамагуста'],
    'Греция': ['Афины', 'Санторини', 'Миконос', 'Крит', 'Родос', 'Салоники', 'Корфу', 'Закинтос', 'Кос', 'Метеоры', 'Дельфы', 'Наксос', 'Парос', 'Лефкада'],
    'Мальта': ['Валлетта', 'Мдина', 'Слима', 'Сент-Джулианс', 'Гозо', 'Буджибба', 'Марсашлокк'],

    // Северная Америка
    'Соединённые Штаты Америки': ['Нью-Йорк', 'Лос-Анджелес', 'Чикаго', 'Майами', 'Лас-Вегас', 'Сан-Франциско', 'Вашингтон', 'Бостон', 'Сиэтл', 'Орландо', 'Хьюстон', 'Даллас', 'Сан-Диего', 'Гонолулу', 'Атланта', 'Денвер', 'Филадельфия', 'Нашвилл', 'Новый Орлеан', 'Портленд', 'Финикс', 'Остин', 'Гранд-Каньон'],
    'Канада': ['Торонто', 'Ванкувер', 'Монреаль', 'Оттава', 'Калгари', 'Эдмонтон', 'Квебек', 'Виктория', 'Галифакс', 'Банф', 'Уистлер', 'Ниагарский водопад', 'Виннипег'],
    'Мексика': ['Мехико', 'Канкун', 'Плая-дель-Кармен', 'Лос-Кабос', 'Гвадалахара', 'Пуэрто-Вальярта', 'Оахака', 'Мерида', 'Тулум', 'Сан-Мигель-де-Альенде', 'Гуанахуато', 'Пуэбла', 'Нижняя Калифорния'],

    // Южная Америка
    'Бразилия': ['Рио-де-Жанейро', 'Сан-Паулу', 'Бразилиа', 'Сальвадор', 'Форталеза', 'Манаус', 'Ресифи', 'Флорианополис', 'Фос-ду-Игуасу', 'Белу-Оризонти', 'Куритиба', 'Натал'],
    'Аргентина': ['Буэнос-Айрес', 'Мендоса', 'Барилоче', 'Игуасу', 'Ушуайя', 'Кордова', 'Сальта', 'Эль-Калафате', 'Пуэрто-Мадрин', 'Росарио'],
    'Колумбия': ['Богота', 'Картахена', 'Медельин', 'Кали', 'Санта-Марта', 'Сан-Андрес', 'Барранкилья', 'Перейра', 'Летисия'],
    'Перу': ['Лима', 'Куско', 'Мачу-Пикчу', 'Арекипа', 'Пуно', 'Уарас', 'Икитос', 'Наска', 'Озеро Титикака'],
    'Чили': ['Сантьяго', 'Вальпараисо', 'Сан-Педро-де-Атакама', 'Остров Пасхи', 'Патагония', 'Винья-дель-Мар', 'Пуэрто-Наталес', 'Торрес-дель-Пайне'],
    'Эквадор': ['Кито', 'Гуаякиль', 'Галапагосские острова', 'Куэнка', 'Баньос', 'Отавало', 'Монтанита'],
    'Боливия': ['Ла-Пас', 'Сукре', 'Санта-Крус', 'Уюни', 'Кочабамба', 'Потоси', 'Оруро', 'Озеро Титикака'],
    'Венесуэла': ['Каракас', 'Маракайбо', 'Остров Маргарита', 'Валенсия', 'Лос-Рокес', 'Мерида', 'Канайма'],
    'Парагвай': ['Асунсьон', 'Сьюдад-дель-Эсте', 'Энкарнасьон', 'Арегуа'],
    'Уругвай': ['Монтевидео', 'Пунта-дель-Эсте', 'Колония-дель-Сакраменто', 'Сальто'],
    'Суринам': ['Парамарибо', 'Ниув-Никкери'],
    'Гайана': ['Джорджтаун', 'Водопад Кайетур', 'Бартика', 'Линден'],

    // Центральная Америка и Карибы
    'Коста-Рика': ['Сан-Хосе', 'Тамариндо', 'Мануэль-Антонио', 'Ареналь', 'Пуэрто-Вьехо', 'Монтеверде', 'Ла-Фортуна', 'Хако'],
    'Панама': ['Панама', 'Бокас-дель-Торо', 'Бокете', 'Острова Сан-Блас', 'Колон', 'Эль-Валье', 'Педаси'],
    'Гватемала': ['Гватемала', 'Антигуа', 'Флорес', 'Чичикастенанго', 'Озеро Атитлан', 'Семук-Чампей', 'Тикаль'],
    'Куба': ['Гавана', 'Варадеро', 'Тринидад', 'Сантьяго-де-Куба', 'Виньялес', 'Кайо-Коко', 'Кайо-Санта-Мария', 'Сьенфуэгос'],
    'Доминиканская Республика': ['Пунта-Кана', 'Санто-Доминго', 'Ла-Романа', 'Пуэрто-Плата', 'Самана', 'Баваро', 'Харабакоа', 'Сосуа'],
    'Ямайка': ['Кингстон', 'Монтего-Бей', 'Очо-Риос', 'Негрил', 'Порт-Антонио', 'Ранс-Эвей'],
    'Багамские острова': ['Нассау', 'Фрипорт', 'Харбор-Айленд', 'Эксума', 'Элеутера', 'Гранд-Багама'],
    'Барбадос': ['Бриджтаун', 'Ойстинс', 'Холтаун', 'Спайтстаун'],
    'Тринидад и Тобаго': ['Порт-оф-Спейн', 'Сан-Фернандо', 'Тобаго', 'Скарборо', 'Краун-Пойнт'],
    'Антигуа и Барбуда': ['Сент-Джонс', 'Инглиш-Харбор', 'Дикенсон-Бей'],
    'Сент-Китс и Невис': ['Бастер', 'Чарлстаун'],
    'Сент-Люсия': ['Кастри', 'Суфриер', 'Родни-Бей', 'Мариго-Бей'],
    'Сент-Винсент': ['Кингстаун', 'Бекия', 'Мустик'],
    'Гренада': ['Сент-Джорджес', 'Гранд-Анс', 'Карриаку'],
    'Доминика': ['Розо', 'Портсмут'],
    'Белиз': ['Белиз-Сити', 'Белмопан', 'Сан-Педро', 'Ки-Колкер', 'Пласенсия', 'Хопкинс'],
    'Гондурас': ['Тегусигальпа', 'Сан-Педро-Сула', 'Роатан', 'Ла-Сейба', 'Утила', 'Копан'],
    'Никарагуа': ['Манагуа', 'Гранада', 'Леон', 'Сан-Хуан-дель-Сур', 'Остров Ометепе', 'Корн-Айлендс'],
    'Сальвадор': ['Сан-Сальвадор', 'Санта-Ана', 'Эль-Тунко', 'Сучитото', 'Хоя-де-Серен'],

    // Африка
    'Южная Африка': ['Кейптаун', 'Йоханнесбург', 'Дурбан', 'Претория', 'Парк Крюгера', 'Стелленбос', 'Гарден-Рут', 'Порт-Элизабет', 'Найзна', 'Дракенсберг'],
    'Марокко': ['Марракеш', 'Фес', 'Касабланка', 'Шефшауэн', 'Танжер', 'Рабат', 'Агадир', 'Эссуэйра', 'Мерзуга', 'Долина Дадес'],
    'Тунис': ['Тунис', 'Сусс', 'Хаммамет', 'Джерба', 'Монастир', 'Сиди-Бу-Саид', 'Дуз', 'Кайруан', 'Эль-Джем'],
    'Кения': ['Найроби', 'Момбаса', 'Масаи-Мара', 'Накуру', 'Диани', 'Малинди', 'Ламу', 'Амбосели', 'Найваша'],
    'Танзания': ['Дар-эс-Салам', 'Занзибар', 'Аруша', 'Килиманджаро', 'Серенгети', 'Нгоронгоро', 'Стоун-Таун', 'Остров Пемба', 'Селус'],
    'Эфиопия': ['Аддис-Абеба', 'Лалибэла', 'Гондэр', 'Аксум', 'Бахр-Дар', 'Харар', 'Горы Сымен', 'Долина Омо'],
    'Уганда': ['Кампала', 'Энтеббе', 'Джинджа', 'Бвинди', 'Форт-Портал', 'Мбале', 'Водопад Мёрчисон'],
    'Руанда': ['Кигали', 'Национальный парк Вулканов', 'Мусанзе', 'Озеро Киву', 'Ньюнгве', 'Бутаре'],
    'Мадагаскар': ['Антананариву', 'Нуси-Бе', 'Анцирабе', 'Морондава', 'Аллея баобабов', 'Иль-Сент-Мари'],
    'Намибия': ['Виндхук', 'Свакопмунд', 'Этоша', 'Соссусфлей', 'Уолфиш-Бей', 'Берег скелетов', 'Каньон Фиш-Ривер'],
    'Ботсвана': ['Габороне', 'Маун', 'Касане', 'Чобе', 'Дельта Окаванго', 'Франсистаун', 'Ната'],
    'Мозамбик': ['Мапуту', 'Бейра', 'Иньямбане', 'Виланкулуш', 'Тофу', 'Архипелаг Базаруто'],
    'Замбия': ['Лусака', 'Ливингстон', 'Водопад Виктория', 'Кафуэ', 'Северная Луангва', 'Сиавонга'],
    'Зимбабве': ['Хараре', 'Булавайо', 'Водопад Виктория', 'Хванге', 'Масвинго', 'Матобо'],
    'Нигерия': ['Лагос', 'Абуджа', 'Кано', 'Ибадан', 'Порт-Харкорт', 'Энугу', 'Кадуна', 'Бенин-Сити'],
    'Гана': ['Аккра', 'Кумаси', 'Кейп-Кост', 'Тамале', 'Элмина', 'Национальный парк Моле'],
    'Сенегал': ['Дакар', 'Сен-Луи', 'Сали', 'Остров Горе', 'Казаманс', 'Тиес'],
    'Камерун': ['Яунде', 'Дуала', 'Лимбе', 'Баменда', 'Криби', 'Бафуссам'],
    'Алжир': ['Алжир', 'Оран', 'Константина', 'Аннаба', 'Сетиф', 'Тлемсен', 'Гардая'],
    'Ливия': ['Триполи', 'Бенгази', 'Лептис-Магна', 'Сабрата', 'Мисурата'],
    'Маврикий': ['Порт-Луи', 'Гранд-Бе', 'Флик-ан-Флак', 'Бель-Омбр', 'Тамарин', 'Остров Родригес'],
    'Сейшельские острова': ['Виктория', 'Маэ', 'Праслин', 'Ла-Диг', 'Остров Силуэт'],
    'Сомали': ['Могадишо', 'Харгейса', 'Бербера'],
    'Судан': ['Хартум', 'Омдурман', 'Порт-Судан', 'Мероэ', 'Кассала'],
    'Южный Судан': ['Джуба', 'Малакаль', 'Бор'],
    'Эритрея': ['Асмэра', 'Массауа', 'Керен'],
    'Джибути': ['Джибути', 'Тадьюра', 'Али-Сабие'],
    'Мали': ['Бамако', 'Тимбукту', 'Дженне', 'Мопти', 'Сегу'],
    'Нигер': ['Ниамей', 'Агадес', 'Зиндер'],
    'Буркина-Фасо': ['Уагадугу', 'Бобо-Диуласо'],
    'Чад': ['Нджамена', 'Абеше', 'Мунду'],
    'Конго': ['Браззавиль', 'Пуэнт-Нуар'],
    'Габон': ['Либревиль', 'Порт-Жантиль', 'Национальный парк Лопе'],
    'Гамбия': ['Банджул', 'Серекунда', 'Бакау'],
    'Бенин': ['Порто-Ново', 'Котону', 'Уида', 'Абомей'],
    'Того': ['Ломе', 'Кара', 'Сокоде'],
    'Гвинея': ['Конакри', 'Нзерекоре', 'Канкан'],
    'Сьерра-Леоне': ['Фритаун', 'Бо', 'Макени'],
    'Либерия': ['Монровия', 'Бьюкенен'],
    'Центральноафриканская Республика': ['Банги'],
    'Экваториальная Гвинея': ['Малабо', 'Бата'],
    'Кабо-Верде': ['Прая', 'Минделу', 'Сал', 'Боа-Виста', 'Санту-Антан'],
    'Сан-Томе и Принсипи': ['Сан-Томе', 'Остров Принсипи'],
    'Коморские острова': ['Морони', 'Муцамуду'],
    'Бурунди': ['Бужумбура', 'Гитега'],
    'Лесото': ['Масеру', 'Таба-Босиу'],
    'Эсватини': ['Мбабане', 'Манзини', 'Долина Эзулвини'],
    'Малави': ['Лилонгве', 'Блантайр', 'Озеро Малави'],
    'Ангола': ['Луанда', 'Бенгела', 'Лобиту', 'Уамбо', 'Лубанго'],
    'Гаити': ['Порт-о-Пренс', 'Кап-Аитьен', 'Жакмель'],

    // Океания
    'Австралия': ['Сидней', 'Мельбурн', 'Брисбен', 'Перт', 'Аделаида', 'Канберра', 'Голд-Кост', 'Кэрнс', 'Тасмания', 'Дарвин', 'Алис-Спрингс', 'Большой Барьерный риф', 'Долина Баросса', 'Улуру'],
    'Новая Зеландия': ['Окленд', 'Веллингтон', 'Квинстаун', 'Крайстчерч', 'Роторуа', 'Данидин', 'Таупо', 'Милфорд-Саунд', 'Хоббитон', 'Кайкоура', 'Абель-Тасман'],
    'Фиджи': ['Сува', 'Нади', 'Денарау', 'Острова Маманука', 'Острова Ясава', 'Коралловый берег'],
    'Самоа': ['Апия', 'Остров Савайи'],
    'Тонга': ['Нукуалофа', 'Вавау'],
    'Вануату': ['Порт-Вила', 'Луганвилль', 'Остров Танна'],
    'Папуа — Новая Гвинея': ['Порт-Морсби', 'Лаэ', 'Маунт-Хаген', 'Горока'],
    'Соломоновы острова': ['Хониара', 'Гизо'],
    'Кирибати': ['Тарава', 'Остров Рождества'],
    'Маршалловы острова': ['Маджуро', 'Кваджалейн'],
    'Микронезия': ['Паликир', 'Чуук', 'Понпеи'],
    'Палау': ['Корор', 'Озеро медуз', 'Скалистые острова'],
    'Науру': ['Ярен'],
    'Тувалу': ['Фунафути'],
    'Мавритания': ['Нуакшот', 'Нуадибу', 'Шингетти'],
  },
};

// O'zbekiston viloyatlari va tumanlari (ichki turizm uchun)
export const UZ_REGIONS: Record<string, string[]> = {
  uz: [
    'Toshkent shahri',
    'Toshkent viloyati',
    'Samarqand viloyati',
    'Buxoro viloyati',
    'Xorazm viloyati',
    'Qashqadaryo viloyati',
    'Surxondaryo viloyati',
    'Navoiy viloyati',
    'Farg\'ona viloyati',
    'Andijon viloyati',
    'Namangan viloyati',
    'Jizzax viloyati',
    'Sirdaryo viloyati',
    'Qoraqalpog\'iston Respublikasi',
  ],
  ru: [
    'Город Ташкент',
    'Ташкентская область',
    'Самаркандская область',
    'Бухарская область',
    'Хорезмская область',
    'Кашкадарьинская область',
    'Сурхандарьинская область',
    'Навоийская область',
    'Ферганская область',
    'Андижанская область',
    'Наманганская область',
    'Джизакская область',
    'Сырдарьинская область',
    'Республика Каракалпакстан',
  ],
};

export const UZ_DISTRICTS: Record<string, Record<string, string[]>> = {
  uz: {
    'Toshkent shahri': ['Bektemir', 'Chilonzor', 'Yakkasaroy', 'Mirobod', 'Mirzo Ulug\'bek', 'Olmazor', 'Sergeli', 'Shayxontoxur', 'Uchtepa', 'Yashnaobod', 'Yunusobod'],
    'Toshkent viloyati': ['Angren', 'Olmaliq', 'Chirchiq', 'Nurafshon', 'Bekobod', 'Ohangaron', 'Yangiyo\'l', 'Bo\'ka', 'Bo\'stonliq', 'Chinoz', 'Qibray', 'Oqqo\'rg\'on', 'Parkent', 'Piskent', 'Quyi Chirchiq', 'O\'rta Chirchiq', 'Zangiota', 'Yuqori Chirchiq'],
    'Samarqand viloyati': ['Samarqand', 'Kattaqo\'rg\'on', 'Bulung\'ur', 'Ishtixon', 'Jomboy', 'Narpay', 'Nurobod', 'Oqdaryo', 'Pastdarg\'om', 'Paxtachi', 'Payariq', 'Toyloq', 'Urgut'],
    'Buxoro viloyati': ['Buxoro', 'Kogon', 'G\'ijduvon', 'Jondor', 'Olot', 'Peshku', 'Qorako\'l', 'Qorovulbozor', 'Romitan', 'Shofirkon', 'Vobkent'],
    'Xorazm viloyati': ['Urganch', 'Xiva', 'Bog\'ot', 'Gurlan', 'Xonqa', 'Hazorasp', 'Qo\'shko\'pir', 'Shovot', 'Tuproqqal\'a', 'Yangiariq', 'Yangibozor'],
    'Qashqadaryo viloyati': ['Qarshi', 'Shahrisabz', 'Kitob', 'Dehqonobod', 'G\'uzor', 'Kasbi', 'Koson', 'Mirishkor', 'Muborak', 'Nishon', 'Chiroqchi', 'Yakkabog\''],
    'Surxondaryo viloyati': ['Termiz', 'Boysun', 'Denov', 'Jarqo\'rg\'on', 'Muzrabod', 'Oltinsoy', 'Qiziriq', 'Qumqo\'rg\'on', 'Sho\'rchi', 'Sherobod', 'Uzun', 'Angor', 'Bandixon'],
    'Navoiy viloyati': ['Navoiy', 'Zarafshon', 'Konimex', 'Karmana', 'Navbahor', 'Nurota', 'Qiziltepa', 'Tomdi', 'Uchquduq', 'Xatirchi'],
    'Farg\'ona viloyati': ['Farg\'ona', 'Marg\'ilon', 'Quva', 'Qo\'qon', 'Beshariq', 'Bog\'dod', 'Buvayda', 'Dang\'ara', 'Furqat', 'O\'zbekiston', 'Rishton', 'So\'x', 'Toshloq', 'Uchko\'prik', 'Yozyovon'],
    'Andijon viloyati': ['Andijon', 'Xonobod', 'Asaka', 'Baliqchi', 'Bo\'z', 'Buloqboshi', 'Izboskan', 'Jalaquduq', 'Marxamat', 'Oltinko\'l', 'Paxtaobod', 'Qo\'rg\'ontepa', 'Shahrixon', 'Ulug\'nor', 'Xo\'jaobod'],
    'Namangan viloyati': ['Namangan', 'Chortoq', 'Chust', 'Kosonsoy', 'Mingbuloq', 'Norin', 'Pop', 'To\'raqo\'rg\'on', 'Uchqo\'rg\'on', 'Uychi', 'Yangiqo\'rg\'on'],
    'Jizzax viloyati': ['Jizzax', 'Do\'stlik', 'Arnasoy', 'Baxmal', 'Forish', 'G\'allaorol', 'Mirzacho\'l', 'Paxtakor', 'Yangiobod', 'Zafarobod', 'Zarbdor', 'Zomin'],
    'Sirdaryo viloyati': ['Guliston', 'Yangiyer', 'Shirin', 'Boyovut', 'Hovos', 'Mirzaobod', 'Oqoltin', 'Sardoba', 'Sayxunobod'],
    'Qoraqalpog\'iston Respublikasi': ['Nukus', 'Mo\'ynoq', 'Beruniy', 'Bo\'zatov', 'Chimboy', 'Ellikqal\'a', 'Kegeyli', 'Qanliko\'l', 'Qo\'ng\'irot', 'Qorao\'zak', 'Shumanay', 'Taxtako\'pir', 'To\'rtko\'l', 'Xo\'jayli'],
  },
  ru: {
    'Город Ташкент': ['Бектемир', 'Чиланзар', 'Яккасарай', 'Мирабад', 'Мирзо Улугбек', 'Алмазар', 'Сергели', 'Шайхантахур', 'Учтепа', 'Яшнабад', 'Юнусабад'],
    'Ташкентская область': ['Ангрен', 'Алмалык', 'Чирчик', 'Нурафшон', 'Бекабад', 'Ахангаран', 'Янгиюль', 'Бука', 'Бостанлык', 'Чиназ', 'Кибрай', 'Аккурган', 'Паркент', 'Пскент', 'Куйи Чирчик', 'Урта Чирчик', 'Зангиата', 'Юкори Чирчик'],
    'Самаркандская область': ['Самарканд', 'Каттакурган', 'Булунгур', 'Иштыхан', 'Джамбай', 'Нарпай', 'Нурабад', 'Акдарья', 'Пастдаргом', 'Пахтачи', 'Пайарык', 'Тайлак', 'Ургут'],
    'Бухарская область': ['Бухара', 'Каган', 'Гиждуван', 'Жондор', 'Алат', 'Пешку', 'Каракуль', 'Коровулбазар', 'Ромитан', 'Шафиркан', 'Вабкент'],
    'Хорезмская область': ['Ургенч', 'Хива', 'Богат', 'Гурлен', 'Ханка', 'Хазарасп', 'Кушкупыр', 'Шават', 'Тупраккала', 'Янгиарык', 'Янгибазар'],
    'Кашкадарьинская область': ['Карши', 'Шахрисабз', 'Китаб', 'Дехканабад', 'Гузар', 'Касби', 'Касан', 'Миришкор', 'Мубарек', 'Нишон', 'Чиракчи', 'Яккабаг'],
    'Сурхандарьинская область': ['Термез', 'Байсун', 'Денау', 'Джаркурган', 'Музрабад', 'Алтынсай', 'Кизирик', 'Кумкурган', 'Шурчи', 'Шерабад', 'Узун', 'Ангор', 'Бандихан'],
    'Навоийская область': ['Навои', 'Зарафшан', 'Конимех', 'Кармана', 'Навбахор', 'Нурата', 'Кызылтепа', 'Тамды', 'Учкудук', 'Хатырчи'],
    'Ферганская область': ['Фергана', 'Маргилан', 'Кува', 'Коканд', 'Бешарык', 'Багдад', 'Бувайда', 'Дангара', 'Фуркат', 'Узбекистан', 'Риштан', 'Сох', 'Ташлак', 'Учкуприк', 'Язъяван'],
    'Андижанская область': ['Андижан', 'Ханабад', 'Асака', 'Балыкчи', 'Буз', 'Булакбаши', 'Избоскан', 'Джалакудук', 'Мархамат', 'Алтынкуль', 'Пахтаабад', 'Кургантепа', 'Шахрихан', 'Улугнор', 'Ходжаабад'],
    'Наманганская область': ['Наманган', 'Чартак', 'Чуст', 'Касансай', 'Мингбулак', 'Нарын', 'Поп', 'Туракурган', 'Учкурган', 'Уйчи', 'Янгикурган'],
    'Джизакская область': ['Джизак', 'Дустлик', 'Арнасай', 'Бахмал', 'Фориш', 'Галляарал', 'Мирзачуль', 'Пахтакор', 'Янгиабад', 'Зафарабад', 'Зарбдар', 'Заамин'],
    'Сырдарьинская область': ['Гулистан', 'Янгиер', 'Ширин', 'Баяут', 'Хавас', 'Мирзаабад', 'Акалтын', 'Сардоба', 'Сайхунабад'],
    'Республика Каракалпакстан': ['Нукус', 'Муйнак', 'Беруни', 'Бозатау', 'Чимбай', 'Элликкала', 'Кегейли', 'Канлыкуль', 'Кунград', 'Караузяк', 'Шуманай', 'Тахтакупыр', 'Турткуль', 'Ходжейли'],
  },
};

export const DOMESTIC_CATEGORIES: Record<string, Record<string, string>> = {
  uz: {
    excursion: 'Ekskursiya',
    nature: 'Tabiat va tog\'lar',
    historical: 'Tarixiy obidalar',
    pilgrimage: 'Ziyorat',
    recreation: 'Dam olish',
    adventure: 'Sarguzasht',
  },
  ru: {
    excursion: 'Экскурсия',
    nature: 'Природа и горы',
    historical: 'Исторические памятники',
    pilgrimage: 'Паломничество',
    recreation: 'Отдых',
    adventure: 'Приключение',
  },
};

export const AIRLINES: string[] = [
  // Central Asia & CIS
  'Uzbekistan Airways',
  'Silk Avia',
  'Qanot Sharq',
  'Air Astana',
  'FlyArystan',
  'SCAT Airlines',
  'Avia Traffic Company',
  'Pegasus Asia',
  'Tajik Air',
  'Somon Air',
  'Turkmenistan Airlines',
  'Azerbaijan Airlines (AZAL)',
  'Buta Airways',
  'Georgian Airways',
  'Armenia Aircompany (Fly Arna)',
  'Air Manas',
  'S7 Airlines',
  'Aeroflot',
  'Ural Airlines',
  'Rossiya Airlines',
  'Pobeda',
  'Nordwind Airlines',
  'Azur Air',
  'Red Wings Airlines',
  'Utair',
  'Yakutia Airlines',
  'Smartavia',
  'IrAero',
  'Belavia',
  'Air Moldova',
  'Ukraine International Airlines (UIA)',
  'SkyUp Airlines',
  'MIAT Mongolian Airlines',
  'Hunnu Air',

  // Turkey
  'Turkish Airlines',
  'Pegasus Airlines',
  'SunExpress',
  'AnadoluJet',
  'Corendon Airlines',
  'Onur Air',
  'Freebird Airlines',

  // Middle East & Gulf
  'Emirates',
  'Etihad Airways',
  'Qatar Airways',
  'flydubai',
  'Air Arabia',
  'Wizz Air Abu Dhabi',
  'Gulf Air',
  'Oman Air',
  'SalamAir',
  'Saudia (Saudi Arabian Airlines)',
  'flynas',
  'Flyadeal',
  'Kuwait Airways',
  'Jazeera Airways',
  'Middle East Airlines (MEA)',
  'Royal Jordanian',
  'Iran Air',
  'Mahan Air',
  'Iraq Airways',
  'EgyptAir',
  'Nile Air',
  'Air Cairo',

  // Asia - East
  'China Southern Airlines',
  'China Eastern Airlines',
  'Air China',
  'Hainan Airlines',
  'Sichuan Airlines',
  'Xiamen Airlines',
  'Shenzhen Airlines',
  'Spring Airlines',
  'Juneyao Airlines',
  'China Express Airlines',
  'Okay Airways',
  'Lucky Air',
  'Tianjin Airlines',
  'Beijing Capital Airlines',
  'Cathay Pacific',
  'HK Express',
  'Hong Kong Airlines',
  'Korean Air',
  'Asiana Airlines',
  'Jin Air',
  'Jeju Air',
  'T\'way Air',
  'Air Busan',
  'Easter Jet',
  'ANA (All Nippon Airways)',
  'Japan Airlines (JAL)',
  'Peach Aviation',
  'Jetstar Japan',
  'Skymark Airlines',
  'StarFlyer',
  'Solaseed Air',
  'Air Do',
  'EVA Air',
  'China Airlines',
  'Starlux Airlines',
  'Tigerair Taiwan',
  'Mandarin Airlines',

  // Asia - Southeast
  'Singapore Airlines',
  'Scoot',
  'Malaysia Airlines',
  'AirAsia',
  'AirAsia X',
  'Firefly',
  'Batik Air',
  'Batik Air Malaysia',
  'Thai Airways',
  'Thai AirAsia',
  'Bangkok Airways',
  'Thai Lion Air',
  'Thai Smile',
  'Nok Air',
  'Nok Scoot',
  'Vietnam Airlines',
  'VietJet Air',
  'Bamboo Airways',
  'Pacific Airlines',
  'Garuda Indonesia',
  'Lion Air',
  'Citilink',
  'Super Air Jet',
  'TransNusa',
  'Sriwijaya Air',
  'NAM Air',
  'Trigana Air Service',
  'Wings Air',
  'Philippine Airlines',
  'Cebu Pacific',
  'AirAsia Philippines',
  'Royal Air Philippines',
  'Myanmar Airways International',
  'Cambodia Angkor Air',
  'Lao Airlines',
  'Royal Brunei Airlines',

  // Asia - South
  'Air India',
  'IndiGo',
  'SpiceJet',
  'Go First',
  'Vistara',
  'AirAsia India',
  'Akasa Air',
  'Alliance Air',
  'SriLankan Airlines',
  'Maldivian',
  'Biman Bangladesh Airlines',
  'US-Bangla Airlines',
  'Nepal Airlines',
  'Buddha Air',
  'Yeti Airlines',
  'Pakistan International Airlines (PIA)',
  'Airblue',
  'Serene Air',

  // Europe - Major
  'Lufthansa',
  'British Airways',
  'Air France',
  'KLM Royal Dutch Airlines',
  'Iberia',
  'ITA Airways',
  'Swiss International Air Lines',
  'Austrian Airlines',
  'Brussels Airlines',
  'Scandinavian Airlines (SAS)',
  'Norwegian Air Shuttle',
  'Finnair',
  'LOT Polish Airlines',
  'TAP Air Portugal',
  'Aer Lingus',
  'Icelandair',
  'PLAY',
  'Aegean Airlines',
  'Olympic Air',
  'Air Serbia',
  'Croatia Airlines',
  'Air Baltic',
  'Czech Airlines',
  'TAROM',
  'Bulgaria Air',
  'Air Albania',
  'Luxair',
  'Air Malta',
  'Cyprus Airways',

  // Europe - Low Cost
  'Ryanair',
  'easyJet',
  'Wizz Air',
  'Vueling',
  'Eurowings',
  'Transavia',
  'Volotea',
  'Condor',
  'TUI fly',
  'Jet2',
  'Lauda',
  'Blue Air',
  'Flyr',
  'Norse Atlantic Airways',
  'Air Europa',
  'Iberia Express',
  'SmartWings',
  'Buzz',
  'Malta Air',
  'Sundair',

  // Africa
  'Ethiopian Airlines',
  'Kenya Airways',
  'South African Airways',
  'Royal Air Maroc',
  'Tunisair',
  'Air Algérie',
  'Rwandair',
  'Air Tanzania',
  'Uganda Airlines',
  'Air Côte d\'Ivoire',
  'ASKY Airlines',
  'Precision Air',
  'Air Mauritius',
  'Air Seychelles',
  'Air Madagascar',
  'Fastjet',
  'Jambojet',
  'FlySafair',
  'Kulula',
  'Air Peace',
  'Dana Air',
  'Overland Airways',
  'TAAG Angola Airlines',
  'LAM Mozambique',
  'Air Botswana',
  'Air Namibia',
  'Air Zimbabwe',
  'Eritrean Airlines',
  'Badr Airlines',

  // Americas - North
  'American Airlines',
  'United Airlines',
  'Delta Air Lines',
  'Southwest Airlines',
  'JetBlue Airways',
  'Alaska Airlines',
  'Spirit Airlines',
  'Frontier Airlines',
  'Hawaiian Airlines',
  'Allegiant Air',
  'Sun Country Airlines',
  'Breeze Airways',
  'Avelo Airlines',
  'Air Canada',
  'WestJet',
  'Porter Airlines',
  'Flair Airlines',
  'Swoop',
  'Aeromexico',
  'Volaris',
  'Viva Aerobus',

  // Americas - Latin & Caribbean
  'LATAM Airlines',
  'LATAM Airlines Brasil',
  'Gol Linhas Aéreas',
  'Azul Brazilian Airlines',
  'Avianca',
  'Copa Airlines',
  'Wingo',
  'JetSMART',
  'SKY Airline',
  'Aerolineas Argentinas',
  'Flybondi',
  'Caribbean Airlines',
  'Bahamasair',
  'Cubana de Aviación',
  'Air Caraïbes',

  // Oceania
  'Qantas',
  'Virgin Australia',
  'Jetstar Airways',
  'Rex Airlines',
  'Bonza',
  'Air New Zealand',
  'Fiji Airways',
  'Air Tahiti Nui',
  'Air Vanuatu',
  'Solomon Airlines',
  'Air Niugini',
  'Samoa Airways',
];
