// Countries with their cities for tour destination selection
export const COUNTRIES = [
  'Afg\'oniston',
  'Albaniya',
  'Jazoir',
  'Andorra',
  'Angola',
  'Antigua va Barbuda',
  'Argentina',
  'Armaniston',
  'Avstraliya',
  'Avstriya',
  'Ozarbayjon',
  'Bagama orollari',
  'Bahrayn',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgiya',
  'Beliz',
  'Benin',
  'Butan',
  'Boliviya',
  'Bosniya va Gersegovina',
  'Botsvana',
  'Braziliya',
  'Bruney',
  'Bolgariya',
  'Burkina-Faso',
  'Burundi',
  'Kabo-Verde',
  'Kambodja',
  'Kamerun',
  'Kanada',
  'Markaziy Afrika Respublikasi',
  'Chad',
  'Chili',
  'Xitoy',
  'Kolumbiya',
  'Komor orollari',
  'Kongo',
  'Kosta-Rika',
  'Xorvatiya',
  'Kuba',
  'Kipr',
  'Chexiya',
  'Daniya',
  'Jibuti',
  'Dominika',
  'Dominikan Respublikasi',
  'Ekvador',
  'Misr',
  'El-Salvador',
  'Ekvatorial Gvineya',
  'Eritreya',
  'Estoniya',
  'Efiopiya',
  'Fiji',
  'Finlandiya',
  'Fransiya',
  'Gabon',
  'Gambiya',
  'Gruziya',
  'Germaniya',
  'Gana',
  'Gretsiya',
  'Grenada',
  'Gvatemala',
  'Gvineya',
  'Gaiti',
  'Gonduras',
  'Vengriya',
  'Islandiya',
  'Hindiston',
  'Indoneziya',
  'Eron',
  'Iroq',
  'Irlandiya',
  'Isroil',
  'Italiya',
  'Yamayka',
  'Yaponiya',
  'Iordaniya',
  'Qozog\'iston',
  'Keniya',
  'Quvayt',
  'Qirg\'iziston',
  'Laos',
  'Latviya',
  'Livan',
  'Liberiya',
  'Liviya',
  'Lixtenshteyn',
  'Litva',
  'Lyuksemburg',
  'Madagaskar',
  'Malavi',
  'Malayziya',
  'Maldiv orollari',
  'Mali',
  'Malta',
  'Mavritaniya',
  'Mavrikiy',
  'Meksika',
  'Moldova',
  'Monako',
  'Mo\'g\'uliston',
  'Chernogoriya',
  'Marokash',
  'Mozambik',
  'Myanma',
  'Namibiya',
  'Nepal',
  'Niderlandiya',
  'Yangi Zelandiya',
  'Nikaragua',
  'Niger',
  'Nigeriya',
  'Shimoliy Koreya',
  'Shimoliy Makedoniya',
  'Norvegiya',
  'Ummon',
  'Pokiston',
  'Panama',
  'Papua-Yangi Gvineya',
  'Paragvay',
  'Peru',
  'Filippin',
  'Polsha',
  'Portugaliya',
  'Qatar',
  'Ruminiya',
  'Rossiya',
  'Ruanda',
  'Saudiya Arabistoni',
  'Senegal',
  'Serbiya',
  'Seyshel orollari',
  'Singapur',
  'Slovakiya',
  'Sloveniya',
  'Somaliya',
  'Janubiy Afrika',
  'Janubiy Koreya',
  'Janubiy Sudan',
  'Ispaniya',
  'Shri-Lanka',
  'Sudan',
  'Surinam',
  'Shvetsiya',
  'Shveytsariya',
  'Suriya',
  'Tayvan',
  'Tojikiston',
  'Tanzaniya',
  'Tailand',
  'Togo',
  'Trinidad va Tobago',
  'Tunis',
  'Turkiya',
  'Turkmaniston',
  'Uganda',
  'Ukraina',
  'Birlashgan Arab Amirliklari',
  'Buyuk Britaniya',
  'AQSh',
  'Urugvay',
  'O\'zbekiston',
  'Venesuela',
  'Vyetnam',
  'Yaman',
  'Zambiya',
  'Zimbabve',
] as const;

// Cities grouped by country
export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  'O\'zbekiston': ['Toshkent', 'Samarqand', 'Buxoro', 'Xiva', 'Namangan', 'Andijon', 'Farg\'ona', 'Nukus', 'Qarshi', 'Navoiy', 'Jizzax', 'Termiz', 'Urganch', 'Guliston', 'Kokand', 'Marg\'ilon', 'Chirchiq', 'Olmaliq', 'Shahrisabz'],
  'Turkiya': ['Istanbul', 'Antaliya', 'Anqara', 'Izmir', 'Bursa', 'Bodrum', 'Kappadokiya', 'Trabzon', 'Alanya', 'Fethiye', 'Marmaris', 'Kemer', 'Side', 'Belek', 'Kusadasi', 'Dalaman', 'Gaziantep', 'Konya'],
  'Birlashgan Arab Amirliklari': ['Dubay', 'Abu-Dabi', 'Sharjah', 'Ajman', 'Ras-al-Xayma', 'Al-Ayn', 'Fujayra'],
  'Misr': ['Qohira', 'Sharm-el-Shayx', 'Xurgada', 'Lyuksor', 'Asvon', 'Aleksandriya', 'Dahab', 'Marsa Alam', 'El-Guna'],
  'Tailand': ['Bangkok', 'Pattaya', 'Phuket', 'Chiang May', 'Krabi', 'Ko Samui', 'Hua Hin', 'Chiang Ray'],
  'Maldiv orollari': ['Male', 'Maafushi', 'Hulhumale'],
  'Malayziya': ['Kuala-Lumpur', 'Langkavi', 'Penang', 'Johor Bahru', 'Kota Kinabalu', 'Malakka'],
  'Indoneziya': ['Bali', 'Jakarta', 'Yogyakarta', 'Lombok', 'Surabaya'],
  'Gretsiya': ['Afina', 'Santorini', 'Mikonos', 'Krit', 'Rodos', 'Korf', 'Saloniki', 'Zakinos'],
  'Italiya': ['Rim', 'Milan', 'Venetsiya', 'Florensiya', 'Neapol', 'Amalfi', 'Sardinia', 'Sitsiliya', 'Turin', 'Verona'],
  'Ispaniya': ['Madrid', 'Barselona', 'Valenisya', 'Sevilya', 'Malaga', 'Mayorka', 'Ibisa', 'Tenerife', 'Gran Kanariya', 'Alikante'],
  'Fransiya': ['Parij', 'Nissa', 'Lion', 'Marsel', 'Kann', 'Strasburg', 'Bordo', 'Monako'],
  'Germaniya': ['Berlin', 'Myunxen', 'Frankfurt', 'Gamburg', 'Kyoln', 'Dyusseldorf', 'Shtutgart', 'Drezden'],
  'Buyuk Britaniya': ['London', 'Mancherster', 'Edinburg', 'Birmingem', 'Glazgo', 'Bristol', 'Oksford', 'Kembrij'],
  'AQSh': ['Nyu-York', 'Los-Anjeles', 'Chikago', 'Las-Vegas', 'Mayami', 'San-Fransisko', 'Vashington', 'Boston', 'Gavai', 'Orlando', 'Syetl', 'San-Diego'],
  'Xitoy': ['Pekin', 'Shanxay', 'Guanchjou', 'Shenzhen', 'Chendu', 'Xangchjou', 'Sian', 'Guilin'],
  'Yaponiya': ['Tokio', 'Osaka', 'Kioto', 'Yokogama', 'Nagoya', 'Sapporo', 'Fukuoka', 'Okinava'],
  'Janubiy Koreya': ['Seul', 'Busan', 'Inchxon', 'Cheju'],
  'Hindiston': ['Dehli', 'Mumbay', 'Goa', 'Jaipur', 'Agra', 'Bangalore', 'Chennai', 'Kolkata', 'Kerala'],
  'Rossiya': ['Moskva', 'Sankt-Peterburg', 'Sochi', 'Kazan', 'Novosibirsk', 'Yekaterinburg', 'Vladivostok', 'Kaliningrad'],
  'Qozog\'iston': ['Ostona', 'Almati', 'Shimkent', 'Turkiston', 'Aktau', 'Atyrau', 'Qaragandi'],
  'Tojikiston': ['Dushanbe', 'Xo\'jand', 'Kulob', 'Istaravshan', 'Panjakent'],
  'Qirg\'iziston': ['Bishkek', 'Osh', 'Jalol-Obod', 'Karakol', 'Issiqko\'l'],
  'Turkmaniston': ['Ashgabat', 'Turkmenobod', 'Dashoguz', 'Mari'],
  'Ozarbayjon': ['Boku', 'Ganja', 'Sheki', 'Gabala', 'Lankeran'],
  'Gruziya': ['Tbilisi', 'Batumi', 'Kutaisi', 'Mestiya', 'Borjomi', 'Sighnaghi'],
  'Armaniston': ['Yerevan', 'Gyumri', 'Sevan', 'Dilijan'],
  'Saudiya Arabistoni': ['Makka', 'Madina', 'Ar-Riyod', 'Jidda', 'Dammam', 'Taif', 'Tabuk', 'Abha'],
  'Iordaniya': ['Ammon', 'Aqaba', 'Petra', 'O\'lik dengiz'],
  'Isroil': ['Quddus', 'Tel-Aviv', 'Haifa', 'Eilat', 'Nazaret', 'O\'lik dengiz'],
  'Qatar': ['Doha', 'Al-Xor', 'Al-Vakra'],
  'Bahrayn': ['Manama', 'Muharraq'],
  'Ummon': ['Masqat', 'Salalah'],
  'Quvayt': ['Quvayt shahri'],
  'Shri-Lanka': ['Kolombo', 'Kandy', 'Galle', 'Ella', 'Sigiriya', 'Bentota'],
  'Vyetnam': ['Xanoy', 'Xoshimin', 'Danang', 'Nyachan', 'Fukuok', 'Xalong', 'Dalat', 'Xoyxon'],
  'Kipr': ['Larnaka', 'Limassol', 'Pafos', 'Ayia-Napa', 'Nikosia', 'Protaras'],
  'Bolgariya': ['Sofiya', 'Varna', 'Burgas', 'Plovdiv', 'Nessebar', 'Qumolqiz sohili'],
  'Chernogoriya': ['Podgorica', 'Budva', 'Kotor', 'Tivat', 'Xerseg-Novi', 'Bar'],
  'Xorvatiya': ['Zagreb', 'Dubrovnik', 'Split', 'Zadar', 'Pula', 'Rovinj'],
  'Chexiya': ['Praga', 'Karlovi Vari', 'Brno', 'Cheski Krumlov'],
  'Vengriya': ['Budapesht', 'Debrecen', 'Xeviz', 'Eger'],
  'Polsha': ['Varshava', 'Krakov', 'Gdansk', 'Vroclav', 'Poznan'],
  'Avstriya': ['Vena', 'Zalsburg', 'Innsbruck', 'Grats'],
  'Shveytsariya': ['Syurix', 'Jeneva', 'Bern', 'Lyusern', 'Interlakin', 'Zermatt'],
  'Portugaliya': ['Lissabon', 'Porto', 'Faro', 'Madeyra', 'Sintra'],
  'Niderlandiya': ['Amsterdam', 'Rotlerdam', 'Gaaga', 'Utrext'],
  'Norvegiya': ['Oslo', 'Bergen', 'Tromsyo', 'Stavanger'],
  'Shvetsiya': ['Stokgolm', 'Gyoteborg', 'Malmyo'],
  'Finlandiya': ['Xelsinki', 'Turku', 'Rovaniemi', 'Tampere'],
  'Daniya': ['Kopengagen', 'Orxus'],
  'Kuba': ['Gavana', 'Varadero', 'Trinidad', 'Santiago-de-Kuba', 'Kayo Koko'],
  'Dominikan Respublikasi': ['Punta-Kana', 'Santo-Domingo', 'La Romana', 'Puerto Plata'],
  'Meksika': ['Kankun', 'Mexiko siti', 'Playa del Karmen', 'Los Kabos', 'Tulum'],
  'Braziliya': ['Rio-de-Janeyro', 'San-Paulu', 'Salvador', 'Fortaleza', 'Iguasu'],
  'Argentina': ['Buenos-Ayres', 'Mendosa', 'Bariloche', 'Iguasu'],
  'Avstraliya': ['Sidni', 'Melburn', 'Brisben', 'Pert', 'Gold Kost', 'Keyns'],
  'Yangi Zelandiya': ['Oklend', 'Kvinstaun', 'Vellington', 'Kraystcherch'],
  'Kanada': ['Toronto', 'Vankuver', 'Monreal', 'Ottava', 'Kalgariy', 'Kebek'],
  'Marokash': ['Marrakesh', 'Fes', 'Kasablanka', 'Shefshaven', 'Agadir', 'Tanger'],
  'Janubiy Afrika': ['Keyptaun', 'Yoxannesburg', 'Durban', 'Kruger parki'],
  'Tanzaniya': ['Zanzibar', 'Dar-es-Salom', 'Kilimanjaro', 'Serengeti'],
  'Keniya': ['Nayrobi', 'Mombasa', 'Masay Mara'],
  'Seyshel orollari': ['Mae', 'Praslin', 'La Dig'],
  'Singapur': ['Singapur'],
  'Filippin': ['Manila', 'Borakay', 'Palavan', 'Sebu'],
  'Nepal': ['Katmandu', 'Pokhara', 'Chitvan'],
  'Kambodja': ['Siem Rip', 'Pnompen', 'Sihanukvil'],
  'Monako': ['Monako'],
  'Tunis': ['Tunis shahri', 'Suss', 'Hammamet', 'Jirba', 'Monastir'],
  'Pokiston': ['Islamobod', 'Karachi', 'Laxor'],
  'Eron': ['Tehron', 'Isfahan', 'Sheroz', 'Tabriz'],
  'Bangladesh': ['Dakka', 'Chittagong', 'Koksbozor'],
};

// Popular airlines
export const AIRLINES = [
  'Uzbekistan Airways',
  'Qanot Sharq (My Sky)',
  'Turkish Airlines',
  'Pegasus Airlines',
  'Anadolu Jet',
  'Emirates',
  'Etihad Airways',
  'Flydubai',
  'Air Arabia',
  'Qatar Airways',
  'Saudia',
  'Flynas',
  'Air Astana',
  'FlyArystan',
  'Aeroflot',
  'S7 Airlines',
  'Rossiya Airlines',
  'Pobeda',
  'Ural Airlines',
  'Azimut',
  'Nordwind Airlines',
  'Red Wings',
  'Tajik Air',
  'Somon Air',
  'Avia Traffic',
  'Turkmenistan Airlines',
  'Azerbaijan Airlines (AZAL)',
  'Buta Airways',
  'Georgian Airways',
  'Wizz Air Abu Dhabi',
  'Lufthansa',
  'SWISS',
  'Austrian Airlines',
  'KLM',
  'Air France',
  'British Airways',
  'Ryanair',
  'EasyJet',
  'Wizz Air',
  'Vueling',
  'ITA Airways (Alitalia)',
  'Iberia',
  'Eurowings',
  'LOT Polish Airlines',
  'Czech Airlines',
  'TAP Air Portugal',
  'SAS (Scandinavian Airlines)',
  'Finnair',
  'Norwegian Air',
  'Aegean Airlines',
  'Air Baltic',
  'Transavia',
  'Condor',
  'TUI Airways',
  'Corendon Airlines',
  'SunExpress',
  'Jazeera Airways',
  'Gulf Air',
  'Oman Air',
  'Kuwait Airways',
  'Royal Jordanian',
  'EgyptAir',
  'Royal Air Maroc',
  'Tunisair',
  'Ethiopian Airlines',
  'Kenya Airways',
  'South African Airways',
  'Air India',
  'IndiGo',
  'SpiceJet',
  'Thai Airways',
  'Bangkok Airways',
  'Thai AirAsia',
  'Vietnam Airlines',
  'VietJet Air',
  'Singapore Airlines',
  'Scoot',
  'Malaysia Airlines',
  'AirAsia',
  'Garuda Indonesia',
  'Lion Air',
  'Cebu Pacific',
  'Philippine Airlines',
  'Korean Air',
  'Asiana Airlines',
  'Japan Airlines (JAL)',
  'ANA (All Nippon Airways)',
  'Peach Aviation',
  'Air China',
  'China Southern Airlines',
  'China Eastern Airlines',
  'Hainan Airlines',
  'Cathay Pacific',
  'EVA Air',
  'Starlux Airlines',
  'American Airlines',
  'Delta Air Lines',
  'United Airlines',
  'Southwest Airlines',
  'JetBlue',
  'Spirit Airlines',
  'Air Canada',
  'WestJet',
  'Aeromexico',
  'Avianca',
  'LATAM Airlines',
  'Copa Airlines',
  'Gol Airlines',
  'Azul Airlines',
  'Cubana de Aviación',
  'Qantas',
  'Air New Zealand',
  'Jetstar',
  'Virgin Australia',
  'Fiji Airways',
  'SriLankan Airlines',
  'Maldivian',
  'Biman Bangladesh Airlines',
  'Pakistan International Airlines (PIA)',
  'Mahan Air',
  'Iran Air',
] as const;
